USE PRJ301_PGNB

--INSERT PRODUCTS
INSERT INTO dbo.Product (productID, productName, type, price, quantity , brand, origin, volume, effect, rate, purchase) VALUES ('PRO0001', 'OstroVit Omega 3 D3+K2', 'Vitamin', '420000', '90', 'OstroVit', 'Poland', '0.12', N'- Tốt cho não bộ, xương khớp, tim mạch, chống đông máu', '8.5', '0');
INSERT INTO dbo.Product (productID, productName, type, price, quantity , brand, origin, volume, effect, rate, purchase) VALUES ('PRO0002', 'OstroVit Melatonin', 'Vitamin', '250000', '300', 'OstroVit', 'Poland', '0.114', N'- 1 sản phẩm thuộc dòng thực phẩm chức năng hỗ trợ cực hiệu quả cho 1 giấc ngủ ngon, sâu giấc, cải thiện rõ rệt chất lượng giấc ngủ.', '8', '0');
INSERT INTO dbo.Product (productID, productName, type, price, quantity , brand, origin, volume, effect, rate, purchase) VALUES ('PRO0003', 'Blackmores BIO C', 'Vitamin', '340000', '150', 'BlackMores', 'Australia', '0.1', N'-  Viên uống bổ sung vitamin C nguồn gốc tự nhiên, giúp bạn cân đối lại hàm lượng vitamin C trong ngày.', '8.7', '0');
INSERT INTO dbo.Product (productID, productName, type, price, quantity , brand, origin, volume, effect, rate, purchase) VALUES ('PRO0004', 'Now L-Arginine 1000mg', 'Vitamin', '570000', '120', 'Now', 'USA', '0.12', N'- cung cấp cho cơ thể một lượng Arginine vừa đủ để phục vụ quá trình trao đổi chất, sản xuất năng lượng và tăng tốc độ lưu thông máu, rất phù hợp với những người hoạt động thể chất thường xuyên.', '7.6', '0');
INSERT INTO dbo.Product (productID, productName, type, price, quantity , brand, origin, volume, effect, rate, purchase) VALUES ('PRO0005', 'NOW NAC 600mg', 'Vitamin', '600000', '250', 'Now', 'USA', '0.09', N'- Sản phẩm giúp bổ sung Vitamin và khoáng chất giúp cung cấp axit amin N-Acetyl-Cysteine cho người dùng.', '8', '0');
INSERT INTO dbo.Product (productID, productName, type, price, quantity , brand, origin, volume, effect, rate, purchase) VALUES ('PRO0006', 'Blackmores Multivitamin for Men', 'Vitamin', '520000', '50', 'BlackMores', 'Australia', '0.09', N'- Tăng cường sức mạnh sinh lý, giúp phái mạnh luôn giữ vững được phong độ đỉnh cao cả về thể chất lẫn tinh thần.', '8.2', '0');
INSERT INTO dbo.Product (productID, productName, type, price, quantity , brand, origin, volume, effect, rate, purchase) VALUES ('PRO0007', 'Platinum Fish Oil 100 viên', 'Vitamin', '290000', '30', 'MuscleTech', 'USA', '0.1', N'- Thành phần 100% dầu cá tự nhiên, là nguồn cung cấp tuyệt vời hai loại axit béo Omega-3 quan trọng nhất là DHA và EPA.', '7.8', '0');
INSERT INTO dbo.Product (productID, productName, type, price, quantity , brand, origin, volume, effect, rate, purchase) VALUES ('PRO0008', 'Ostrovit Testo Booster 90 viên', 'Vitamin', '320000', '20', 'OstroVit', 'Poland', '0.07', N'- Công dụng chính là giúp người dùng tăng hormone nam testosterone tự nhiên, nâng cao sức khỏe sinh lý, thúc đẩy phát triển cơ bắp và tập luyện hiệu quả hơn.', '8', '0');
INSERT INTO dbo.Product (productID, productName, type, price, quantity , brand, origin, volume, effect, rate, purchase) VALUES ('PRO0009', 'AGGRO 168 viên', 'Vitamin', '890000', '20', 'Nutrabolic', 'Canada', '0.12', N' - Sản phẩm có chứa kẽm và magie tăng hóc môn nam giới và tăng sinh lý nam giới tuyệt vời nhất từ trước tới.', '9', '0');
INSERT INTO dbo.Product (productID, productName, type, price, quantity , brand, origin, volume, effect, rate, purchase) VALUES ('PRO0010', 'EVL Women’s Multivitamin 120 viên', 'Vitamin', '450000', '35', 'EVL', 'USA', '0.12', N'- được thiết kế dành riêng cho phái nữ với đầy đủ nhóm Vitamin, khoáng chất và các hợp chất chống oxy hóa quan trọng nhằm đáp ứng nhu cầu dinh dưỡng mỗi ngày.', '8.7', '0');
INSERT INTO dbo.Product (productID, productName, type, price, quantity , brand, origin, volume, effect, rate, purchase) VALUES ('PRO0011', 'Rule1 Protein 5lbs', 'Protein', '1680000', '100', 'Rule1', 'USA', '2.2', N'- Các loại whey protein cô lập và thủy phân rất tốt cho các vận động viên và những người xây dựng cơ thể, những người đang tìm kiếm các Axit Amin có tác dụng nhanh để sửa chữa và phục hồi cơ bắp.', '9', '0');
INSERT INTO dbo.Product (productID, productName, type, price, quantity , brand, origin, volume, effect, rate, purchase) VALUES ('PRO0012', 'Platinum HydroWhey 3.5lbs 1.59kg', 'Protein', '1890000', '50', 'Optimum Nutrition’s', 'USA', '1.59', N'- Sản phẩm tinh khiết nhất, dễ dàng hấp thụ giúp xây dựng cơ bắp hiệu quả trong thời gian ngắn nhất. Hydrowwhey dễ tan, không có chất béo, cholesterol.', '8.6', '0');
INSERT INTO dbo.Product (productID, productName, type, price, quantity , brand, origin, volume, effect, rate, purchase) VALUES ('PRO0013', 'Vegan Pro 2.1kg', 'Protein', '1350000', '20', 'Applied Nutrition', 'UK', '2.1', N'- sản phẩm protein với sự kết hợp hoàn hảo nguồn Protein thực vật từ các loại đậu, gạo lứt mang đến chất lượng cao cấp với đầy đủ axit amin thiết yếu.', '7.8', '0');
INSERT INTO dbo.Product (productID, productName, type, price, quantity , brand, origin, volume, effect, rate, purchase) VALUES ('PRO0014', 'Amix gold Whey protein Isolate 5lbs', 'Protein', '1890000', '10', 'Amix', 'UK', '2.7', N'- Một sản phẩm bổ sung Whey protein isolate của hãng Amix, đáp ứng nhu cầu về nguồn đạm chất lượng cho cơ bắp. Amix Gold chính là điều kiện cần để gymer rút ngắn hành trình xây dựng cơ bắp của mình.', '8.5', '0');
INSERT INTO dbo.Product (productID, productName, type, price, quantity , brand, origin, volume, effect, rate, purchase) VALUES ('PRO0015', 'NitroTech 10lbs 4.5kg', 'Protein', '3290000', '5', 'Nitro Tech', 'USA', '4.5', N'- Sản phẩm giúp phát triển cơ bắp cung cấp nhiều protein nhất,và không pha trộn nhiều chất béo, đường carbs cũng như tạp chất giống các loại protein khác.', '7.3', '0');
INSERT INTO dbo.Product (productID, productName, type, price, quantity , brand, origin, volume, effect, rate, purchase) VALUES ('PRO0016', 'Gold Standard 100% Casein 4lbs 1.82kg', 'Protein', '1970000', '25', 'Optimum Nutrition’s', 'USA', '1.82', N'- Dòng sản phẩm cao cấp giúp bạn phục hồi và cung cấp đủ năng lượng về đêm để nuôi dưỡng, phục hồi, tái tạo và phát triển các mô cơ bắp.', '8.5', '0');
INSERT INTO dbo.Product (productID, productName, type, price, quantity , brand, origin, volume, effect, rate, purchase) VALUES ('PRO0017', 'ISO HD 5lbs 100% Isolate', 'Protein', '1490000', '15', 'BPI Sport', 'USA', '2.27', N'- Protein calo thấp, tinh khiết nhất cung cấp 25 gram Protein siêu cao cấp 100% Whey Protein Isolate mỗi khẩu phần. Với công nghệ tiên tiến hương vị sữa của bạn đã trở nên ngon hơn rất nhiều.', '8', '0');
INSERT INTO dbo.Product (productID, productName, type, price, quantity , brand, origin, volume, effect, rate, purchase) VALUES ('PRO0018', 'Labrada Lean Pro 8 5lbs 2.27kg', 'Protein', '1690000', '20', 'Labrada', 'USA', '2.27', N'- Bữa ăn nhanh, thông minh với Labrada Lean Pro 8 5lbs (2,27kg) sẽ giúp cho cơ bắp của bạn lớn hơn, mạnh mẽ hơn và gọn gàng nhanh chóng hơn bao giờ hết giúp bạn chống dị hóa cơ.', '7.9', '0');
INSERT INTO dbo.Product (productID, productName, type, price, quantity , brand, origin, volume, effect, rate, purchase) VALUES ('PRO0019', 'Nutrabolics HydroPure 4.5lbs', 'Protein', '1850000', '30', 'Nutrabolic', 'Canada', '2.04', N'- Sản phẩm được loại bỏ các chất béo, lactose và protein predigest để hình thành các chuỗi polypeptide nhỏ của axit amin hỗ trợ hình thành và cải tạo cơ bắp!', '8.2', '0');
INSERT INTO dbo.Product (productID, productName, type, price, quantity , brand, origin, volume, effect, rate, purchase) VALUES ('PRO0020', 'Nutrex EAA Hydration 30 servings', 'EAA', '650000', '20', 'Nutrex', 'USA', '4', N'- Đây là một sản phẩm nổi bật trong cả 2 chuỗi Axit Amin thiết yếu (EAA) và Axit Amin chuỗi nhánh (BCAA), cung cấp cho cơ thể một EAA đầy đủ, hiệu quả bao gồm cả BCAA cần thiết để tăng tổng hợp chất protein ở trong cơ bắp.', '7.3', '0');
INSERT INTO dbo.Product (productID, productName, type, price, quantity , brand, origin, volume, effect, rate, purchase) VALUES ('PRO0021', 'Mutant BCAA 90 servings', 'BCAA', '1390000', '30', 'Mutant', 'Canada', '1.1', N'- BCAA được các vận động viên cũng như những người chơi thể thao chuyên nghiệp hoặc nghiệp như sử dụng với chất năng hồi phục cơ bắp, nhưng ít ai biết được rằng BCAA có thể sử dụng dùng để kích thích làm cho mình ăn nhiều hơn và hấp thu các chất dinh dưỡng nhanh hơn.', '8.8', '0');
INSERT INTO dbo.Product (productID, productName, type, price, quantity , brand, origin, volume, effect, rate, purchase) VALUES ('PRO0022', 'Ostrovit Apple Fiber 40 servings', 'fiber', '180000', '200', 'OstroVit', 'Poland', '0.66', N'- viên uống bổ sung chất xơ, điều hòa huyết áp, giảm cholesterol, cho hệ tiêu hóa khỏe mạnh.', '7.5', '0');
INSERT INTO dbo.Product (productID, productName, type, price, quantity , brand, origin, volume, effect, rate, purchase) VALUES ('PRO0023', 'EVL Stacked Greens Raw 30 servings', 'fiber', '490000', '250', 'EVL', 'USA', '0.76', N'- viên uống bổ sung chất xơ, điều hòa huyết áp, giảm cholesterol, cho hệ tiêu hóa khỏe mạnh.', '6.5', '0');
INSERT INTO dbo.Product (productID, productName, type, price, quantity , brand, origin, volume, effect, rate, purchase) VALUES ('PRO0024', 'Psyllium Husk Caps', 'fiber', '560000', '150', 'Now', 'USA', '0.6', N'- Sản phẩm hỗ trợ bổ sung chất xơ được chiết xuất từ rau quả tự nhiên, hỗ trợ nhuận tràng và giảm táo bón, hỗ trợ giảm cholesterol trong máu. Định lượng: mỗi hộp chứa 30 viên. - Dạng bào chế: viên nén.', '7.7', '0');
INSERT INTO dbo.Product (productID, productName, type, price, quantity , brand, origin, volume, effect, rate, purchase) VALUES ('PRO0025', 'Certified Organic Fiber-3 powder 16 oz', 'fiber', '350000', '200', 'Now', 'USA', '0.66', N'- viên uống bổ sung chất xơ, điều hòa huyết áp, giảm cholesterol, cho hệ tiêu hóa khỏe mạnh.', '9', '0');
INSERT INTO dbo.Product (productID, productName, type, price, quantity , brand, origin, volume, effect, rate, purchase) VALUES ('PRO0026', 'Kirkland Optifiber 730g', 'fiber', '550000', '50', 'Kirkland', 'USA', '0.76', N'- Kirkland Optifiber cung cấp chất xơ cho cơ thể, thích hợp với những người ít ăn rau củ trái cây. Ngăn ngừa táo bón, hỗ trợ tiêu hóa tốt, đồng thời ngừa ung thư ruột kết, đại tràng, trĩ (do táo bón)', '8.6', '0');
INSERT INTO dbo.Product (productID, productName, type, price, quantity , brand, origin, volume, effect, rate, purchase) VALUES ('PRO0027', 'KIRKLAND FIBER CAPSULE', 'fiber', '674000', '20', 'Kirkland', 'USA', '0.6', N'- viên uống bổ sung chất xơ, điều hòa huyết áp, giảm cholesterol, cho hệ tiêu hóa khỏe mạnh.', '7.9', '0');
INSERT INTO dbo.Product (productID, productName, type, price, quantity , brand, origin, volume, effect, rate, purchase) VALUES ('PRO0028', 'Meta Mucil Daily Fiber Supplement – Orange Smooth Sugar Free', 'fiber', '871000', '100', 'MetaMucil', 'USA', '0.66', N'- 100% Psyllium giúp hỗ trợ điều trị táo bón, ổn định đường huyết, bảo vệ tim mạch và kiểm soát lượng cholesterol trong máu. Bên cạnh đó, sẽ giúp giảm cảm giác đói trong các bữa ăn, tăng cường sức đề kháng và hệ miễn dịch cho cơ thể.', '8.2', '0');
INSERT INTO dbo.Product (productID, productName, type, price, quantity , brand, origin, volume, effect, rate, purchase) VALUES ('PRO0029', 'Thuốc bổ sung chất xơ Nutrilite Amway', 'fiber', '595000', '40', 'Nutrilife', 'India', '0.55', N'- Sản phẩm hỗ trợ bổ sung chất xơ được chiết xuất từ rau quả tự nhiên, hỗ trợ nhuận tràng và giảm táo bón, hỗ trợ giảm cholesterol trong máu. Định lượng: mỗi hộp chứa 30 viên. - Dạng bào chế: viên nén.', '6.6', '0');
INSERT INTO dbo.Product (productID, productName, type, price, quantity , brand, origin, volume, effect, rate, purchase) VALUES ('PRO0030', 'Huge Supplements Formula XII', 'carbohydrate', '1516580', '20', 'HUGE', 'USA', '1.2', N'- Thực phẩm bổ sung trong và sau tập luyện này được thiết kế để cung cấp năng lượng lâu dài giúp bạn vượt qua các buổi tập luyện mệt mỏi hoặc giúp bạn hài lòng sau khi tập luyện xong.', '7.8', '0');
INSERT INTO dbo.Product (productID, productName, type, price, quantity , brand, origin, volume, effect, rate, purchase) VALUES ('PRO0031', 'Transparent Labs Carb Powder', 'carbohydrate', '1060639', '20', 'Transparent', 'USA', '1.5', N'- Đây không phải là đồ uống thể thao truyền thống chứa nhiều đường khiến dạ dày của bạn quặn lại. Trái ngược với carbohydrate trọng lượng phân tử thấp như dextrose, Cluster Dextrin®... Chúng tôi cũng khuyên bạn nên sử dụng TL Carb Powder ngay trước khi tập luyện để thúc đẩy quá trình tập luyện của bạn và tăng cường hiệu suất thể thao', '9.1', '0');
INSERT INTO dbo.Product (productID, productName, type, price, quantity , brand, origin, volume, effect, rate, purchase) VALUES ('PRO0032', 'Swolverine Clean Carbs', 'carbohydrate', '1414264', '20', 'Swolverine', 'USA', '1.3', N'- được làm bằng 100% siêu thực phẩm nguyên chất thực sự từ carbohydrate phức hợp, bao gồm Khoai lang, Khoai mỡ, Yến mạch và Quả việt quất. Bốn thành phần này cung cấp năng lượng lâu dài và bền vững mà cơ thể bạn cần để thúc đẩy hiệu suất và tối ưu hóa quá trình phục hồi.', '8.7', '0');
INSERT INTO dbo.Product (productID, productName, type, price, quantity , brand, origin, volume, effect, rate, purchase) VALUES ('PRO0033', 'Xwerks Motion', 'carbohydrate', '1155175', '20', 'Xwerks', 'USA', '0.95', N'- Cluster Dextrin dễ dàng được trộn lẫn, tiêu hóa (không đầy hơi) và nhanh chóng đi qua dạ dày của bạn - bổ sung mức năng lượng nhanh hơn bất kỳ nguồn carb nào khác, bao gồm maltodextrin, dextrose và ngô nếp.', '7.1', '0');
INSERT INTO dbo.Product (productID, productName, type, price, quantity , brand, origin, volume, effect, rate, purchase) VALUES ('PRO0034', 'NOW Sports Nutrition Waxy Maize', 'carbohydrate', '347495', '20', 'Now', 'USA', '2.4', N'- Đó là một loại tinh bột phức hợp có nguồn gốc từ ngô không biến đổi gen có hàm lượng amylopectin cao tự nhiên, một loại polysacarit phân nhánh cao, có trọng lượng phân tử cao.', '8.3', '0');
INSERT INTO dbo.Product (productID, productName, type, price, quantity , brand, origin, volume, effect, rate, purchase) VALUES ('PRO0035', 'Redcon1 Cluster Bomb', 'carbohydrate', '1060639', '20', 'Redcon1', 'UK', '0.825', N'- Giúp tăng cơ bắp trong quá trình tập luyện - Bột carb Cluster Bomb với dextrin tuần hoàn dành cho những người tập thể thao thuộc mọi kỹ năng đang tìm kiếm dinh dưỡng trong quá trình tập luyện để mở khóa cơ bắp và sức mạnh mới.', '6.7', '0');
INSERT INTO dbo.Product (productID, productName, type, price, quantity , brand, origin, volume, effect, rate, purchase) VALUES ('PRO0036', 'Labrada Muscle Mass Gainer 12lbs 5.4Kg', 'mass', '1750000', '30', 'Labrada', 'USA', '5.4', N'- dòng sữa tăng cân cho người gầy thiếu cân, khó hấp thụ, bởi chỉ với một lượng phù hợp được hấp thụ Mass Gainer làm cơ thể dễ thích nghi, tăng cân lành mạnh.', '7.9', '0');
INSERT INTO dbo.Product (productID, productName, type, price, quantity , brand, origin, volume, effect, rate, purchase) VALUES ('PRO0037', 'Mass Fusion 12lbs 5.4kg', 'mass', '1790000', '20', 'Nutrabolic', 'Canada', '5.4', N'- phù hợp với người gầy muốn tăng cân với nguồn năng lượng sạch để duy trì cân nặng và hỗ trợ tăng cơ rất tốt.', '9.2', '0');

--INSERT FOODS
INSERT INTO Food (foodID, foodName, category, size, caloricintake, carbohydrate, fiber, protein, fat, water) VALUES ('FD00001', 'apricot', 'fruit', '155', '74', '17', '3.1', '2.2', '0.6', '133.84');
INSERT INTO Food (foodID, foodName, category, size, caloricintake, carbohydrate, fiber, protein, fat, water) VALUES ('FD00002', 'avocado', 'fruit', '230', '368', '20', '15', '4.6', '34', '168.43');
INSERT INTO Food (foodID, foodName, category, size, caloricintake, carbohydrate, fiber, protein, fat, water) VALUES ('FD00003', 'Banana', 'fruit', '225', '200', '51', '5.9', '2.5', '0.7', '168.55');
INSERT INTO Food (foodID, foodName, category, size, caloricintake, carbohydrate, fiber, protein, fat, water) VALUES ('FD00004', 'Blackberry', 'fruit', '144', '62', '14', '7.6', '2', '0.7', '126.94');
INSERT INTO Food (foodID, foodName, category, size, caloricintake, carbohydrate, fiber, protein, fat, water) VALUES ('FD00005', 'Blueberry', 'fruit', '148', '84', '21', '3.6', '1.1', '0.5', '124.63');
INSERT INTO Food (foodID, foodName, category, size, caloricintake, carbohydrate, fiber, protein, fat, water) VALUES ('FD00006', 'Cherry', 'fruit', '150', '95', '24', '3.2', '1.6', '0.3', '123.38');
INSERT INTO Food (foodID, foodName, category, size, caloricintake, carbohydrate, fiber, protein, fat, water) VALUES ('FD00007', 'Coconut', 'fruit', '85', '301', '13', '7.7', '2.8', '28', '39.94');
INSERT INTO Food (foodID, foodName, category, size, caloricintake, carbohydrate, fiber, protein, fat, water) VALUES ('FD00008', 'Cucumber', 'fruit', '120', '18', '4.4', '0.6', '0.8', '0.1', '114.28');
INSERT INTO Food (foodID, foodName, category, size, caloricintake, carbohydrate, fiber, protein, fat, water) VALUES ('FD00009', 'Durian', 'fruit', '243', '357', '66', '9', '3.6', '13', '157.93');
INSERT INTO Food (foodID, foodName, category, size, caloricintake, carbohydrate, fiber, protein, fat, water) VALUES ('FD00010', 'Dragon fruit', 'fruit', '170', '102', '22', '5', '2', '0', '145.25');
INSERT INTO Food (foodID, foodName, category, size, caloricintake, carbohydrate, fiber, protein, fat, water) VALUES ('FD00011', 'Fig', 'fruit', '50', '37', '9.6', '1.5', '0.4', '0.2', '39.55');
INSERT INTO Food (foodID, foodName, category, size, caloricintake, carbohydrate, fiber, protein, fat, water) VALUES ('FD00012', 'Gooseberry', 'fruit', '150', '66', '15', '6.5', '1.3', '0.9', '131.81');
INSERT INTO Food (foodID, foodName, category, size, caloricintake, carbohydrate, fiber, protein, fat, water) VALUES ('FD00013', 'Grape', 'fruit', '150', '104', '27', '1.4', '1.1', '0.2', '120.81');
INSERT INTO Food (foodID, foodName, category, size, caloricintake, carbohydrate, fiber, protein, fat, water) VALUES ('FD00014', 'Guava', 'fruit', '165', '112', '24', '8.9', '4.2', '1.6', '133.32');
INSERT INTO Food (foodID, foodName, category, size, caloricintake, carbohydrate, fiber, protein, fat, water) VALUES ('FD00015', 'Jackfruit', 'fruit', '100', '211', '25', '3.5', '3.5', '12', '100');
INSERT INTO Food (foodID, foodName, category, size, caloricintake, carbohydrate, fiber, protein, fat, water) VALUES ('FD00016', 'Plum', 'fruit', '155', '71', '18', '2.2', '1.1', '0.4', '135.21');
INSERT INTO Food (foodID, foodName, category, size, caloricintake, carbohydrate, fiber, protein, fat, water) VALUES ('FD00017', 'Kiwifruit', 'fruit', '180', '110', '26', '5.4', '2.1', '0.1', '149.53');
INSERT INTO Food (foodID, foodName, category, size, caloricintake, carbohydrate, fiber, protein, fat, water) VALUES ('FD00018', 'Kumquat', 'fruit', '185', '131', '29', '12', '3.5', '1.6', '149.57');
INSERT INTO Food (foodID, foodName, category, size, caloricintake, carbohydrate, fiber, protein, fat, water) VALUES ('FD00019', 'Lemon', 'fruit', '200', '58', '19', '5.6', '2.2', '0.6', '177.96');
INSERT INTO Food (foodID, foodName, category, size, caloricintake, carbohydrate, fiber, protein, fat, water) VALUES ('FD00020', 'Lime', 'fruit', '200', '60', '21', '5.6', '1.4', '0.4', '176.52');
INSERT INTO Food (foodID, foodName, category, size, caloricintake, carbohydrate, fiber, protein, fat, water) VALUES ('FD00021', 'Mango', 'fruit', '165', '99', '25', '0.6', '1.4', '0.6', '137.71');
INSERT INTO Food (foodID, foodName, category, size, caloricintake, carbohydrate, fiber, protein, fat, water) VALUES ('FD00022', 'Watermelon', 'fruit', '154', '46', '12', '0.6', '0.9', '0.2', '140.83');
INSERT INTO Food (foodID, foodName, category, size, caloricintake, carbohydrate, fiber, protein, fat, water) VALUES ('FD00023', 'Mulberry', 'fruit', '140', '60', '14', '2.4', '2', '0.5', '122.75');
INSERT INTO Food (foodID, foodName, category, size, caloricintake, carbohydrate, fiber, protein, fat, water) VALUES ('FD00024', 'Orange', 'fruit', '180', '85', '21', '4.3', '1.7', '0.2', '156.15');
INSERT INTO Food (foodID, foodName, category, size, caloricintake, carbohydrate, fiber, protein, fat, water) VALUES ('FD00025', 'Papaya', 'fruit', '230', '99', '25', '3.9', '1.1', '0.6', '202.54');
INSERT INTO Food (foodID, foodName, category, size, caloricintake, carbohydrate, fiber, protein, fat, water) VALUES ('FD00026', 'Passionfruit', 'fruit', '236', '229', '55', '25', '5', '1.7', '150.36');
INSERT INTO Food (foodID, foodName, category, size, caloricintake, carbohydrate, fiber, protein, fat, water) VALUES ('FD00027', 'Peach', 'fruit', '155', '65', '16', '2.3', '1.4', '0.4', '136.87');
INSERT INTO Food (foodID, foodName, category, size, caloricintake, carbohydrate, fiber, protein, fat, water) VALUES ('FD00028', 'Pear', 'fruit', '125', '71', '19', '3.9', '0.5', '0.2', '104.95');
INSERT INTO Food (foodID, foodName, category, size, caloricintake, carbohydrate, fiber, protein, fat, water) VALUES ('FD00029', 'Persimmon', 'fruit', '170', '119', '32', '6.1', '1', '0.3', '136.54');
INSERT INTO Food (foodID, foodName, category, size, caloricintake, carbohydrate, fiber, protein, fat, water) VALUES ('FD00030', 'Pineapple', 'fruit', '165', '83', '22', '2.3', '0.9', '0.2', '141.9');
INSERT INTO Food (foodID, foodName, category, size, caloricintake, carbohydrate, fiber, protein, fat, water) VALUES ('FD00031', 'Pineberry', 'fruit', '100', '29', '5.1', '1.1', '0.7', '0', '67.24');
INSERT INTO Food (foodID, foodName, category, size, caloricintake, carbohydrate, fiber, protein, fat, water) VALUES ('FD00032', 'Quince', 'fruit', '92', '52', '14', '1.8', '0.4', '0.1', '77.1');
INSERT INTO Food (foodID, foodName, category, size, caloricintake, carbohydrate, fiber, protein, fat, water) VALUES ('FD00033', 'Raspberry', 'fruit', '123', '64', '15', '8', '1.5', '0.8', '105.47');
INSERT INTO Food (foodID, foodName, category, size, caloricintake, carbohydrate, fiber, protein, fat, water) VALUES ('FD00034', 'Soursop', 'fruit', '225', '149', '38', '7.4', '2.3', '0.7', '182.61');
INSERT INTO Food (foodID, foodName, category, size, caloricintake, carbohydrate, fiber, protein, fat, water) VALUES ('FD00035', 'Starfruit', 'fruit', '100', '31', '6.7', '2.8', '1', '0.3', '91.38');
INSERT INTO Food (foodID, foodName, category, size, caloricintake, carbohydrate, fiber, protein, fat, water) VALUES ('FD00036', 'Strawberry', 'fruit', '100', '31', '7.6', '1.8', '0.6', '0.2', '91.1');
INSERT INTO Food (foodID, foodName, category, size, caloricintake, carbohydrate, fiber, protein, fat, water) VALUES ('FD00037', 'Tamarind', 'fruit', '120', '287', '75', '6.1', '3.4', '0.3', '37.68');
INSERT INTO Food (foodID, foodName, category, size, caloricintake, carbohydrate, fiber, protein, fat, water) VALUES ('FD00038', 'Artichoke', 'vegetables', '150', '80', '18', '8.6', '4.3', '0.5', '126.12');
INSERT INTO Food (foodID, foodName, category, size, caloricintake, carbohydrate, fiber, protein, fat, water) VALUES ('FD00039', 'Asparagus', 'vegetables', '134', '27', '5.2', '2.8', '3', '0.2', '124.91');
INSERT INTO Food (foodID, foodName, category, size, caloricintake, carbohydrate, fiber, protein, fat, water) VALUES ('FD00040', 'Eggplant', 'vegetables', '82', '21', '4.8', '2.5', '0.8', '0.1', '75.69');
INSERT INTO Food (foodID, foodName, category, size, caloricintake, carbohydrate, fiber, protein, fat, water) VALUES ('FD00041', 'Beet', 'vegetables', '136', '58', '13', '3.8', '2.2', '0.2', '119.11');
INSERT INTO Food (foodID, foodName, category, size, caloricintake, carbohydrate, fiber, protein, fat, water) VALUES ('FD00042', 'Bok Choy', 'vegetables', '70', '9', '1.5', '0.7', '1.1', '0.1', '66.72');
INSERT INTO Food (foodID, foodName, category, size, caloricintake, carbohydrate, fiber, protein, fat, water) VALUES ('FD00043', 'Broccoli', 'vegetables', '91', '31', '6', '2.4', '2.6', '0.3', '81.26');
INSERT INTO Food (foodID, foodName, category, size, caloricintake, carbohydrate, fiber, protein, fat, water) VALUES ('FD00044', 'Broccolini', 'vegetables', '122', '37', '7.3', '3.7', '2.4', '0.6', '100');
INSERT INTO Food (foodID, foodName, category, size, caloricintake, carbohydrate, fiber, protein, fat, water) VALUES ('FD00045', 'Broccoli Raab', 'vegetables', '40', '8', '1.1', '1.1', '1.3', '0.2', '37.02');
INSERT INTO Food (foodID, foodName, category, size, caloricintake, carbohydrate, fiber, protein, fat, water) VALUES ('FD00046', 'Brussels Sprouts', 'vegetables', '88', '38', '7.9', '3.3', '3', '0.3', '75.68');
INSERT INTO Food (foodID, foodName, category, size, caloricintake, carbohydrate, fiber, protein, fat, water) VALUES ('FD00047', 'Chinese Cabbage', 'vegetables', '90', '12', '2', '0.9', '1.4', '0.2', '85.79');
INSERT INTO Food (foodID, foodName, category, size, caloricintake, carbohydrate, fiber, protein, fat, water) VALUES ('FD00048', 'Green Cabbage', 'vegetables', '90', '23', '5.2', '2.3', '1.2', '0.1', '82.96');
INSERT INTO Food (foodID, foodName, category, size, caloricintake, carbohydrate, fiber, protein, fat, water) VALUES ('FD00049', 'Purple Cabbage', 'vegetables', '89', '22', '5.2', '2.2', '1.1', '0.1', '82.04');
INSERT INTO Food (foodID, foodName, category, size, caloricintake, carbohydrate, fiber, protein, fat, water) VALUES ('FD00050', 'Savoy Cabbage', 'vegetables', '145', '35', '7.8', '4.1', '2.6', '0.1', '133.4');
INSERT INTO Food (foodID, foodName, category, size, caloricintake, carbohydrate, fiber, protein, fat, water) VALUES ('FD00051', 'Carrots', 'vegetables', '128', '52', '12', '3.6', '1.2', '0.3', '113.01');
INSERT INTO Food (foodID, foodName, category, size, caloricintake, carbohydrate, fiber, protein, fat, water) VALUES ('FD00052', 'Cauliflower', 'vegetables', '100', '25', '10', '5.3', '1.5', '0.2', '71.2');
INSERT INTO Food (foodID, foodName, category, size, caloricintake, carbohydrate, fiber, protein, fat, water) VALUES ('FD00053', 'Celeriac', 'vegetables', '156', '66', '14', '2.8', '2.3', '0.5', '137.28');
INSERT INTO Food (foodID, foodName, category, size, caloricintake, carbohydrate, fiber, protein, fat, water) VALUES ('FD00054', 'Celery', 'vegetables', '101', '14', '3', '1.6', '0.7', '0.2', '96.38');
INSERT INTO Food (foodID, foodName, category, size, caloricintake, carbohydrate, fiber, protein, fat, water) VALUES ('FD00055', 'Chard (Red and Swiss)', 'vegetables', '36', '6', '1.4', '0.6', '0.7', '0.1', '33.36');
INSERT INTO Food (foodID, foodName, category, size, caloricintake, carbohydrate, fiber, protein, fat, water) VALUES ('FD00056', 'Chicory', 'vegetables', '240', '17', '3.4', '0', '0.5', '0', '235.44');
INSERT INTO Food (foodID, foodName, category, size, caloricintake, carbohydrate, fiber, protein, fat, water) VALUES ('FD00057', 'Corn', 'vegetables', '150', '129', '28', '3', '4.9', '2', '114.08');
INSERT INTO Food (foodID, foodName, category, size, caloricintake, carbohydrate, fiber, protein, fat, water) VALUES ('FD00058', 'Cress', 'vegetables', '50', '16', '2.8', '0.6', '1.3', '0.4', '44.7');
INSERT INTO Food (foodID, foodName, category, size, caloricintake, carbohydrate, fiber, protein, fat, water) VALUES ('FD00059', 'Cucumbers', 'vegetables', '120', '18', '4.4', '0.6', '0.8', '0.1', '114.28');
INSERT INTO Food (foodID, foodName, category, size, caloricintake, carbohydrate, fiber, protein, fat, water) VALUES ('FD00060', 'Daikon', 'vegetables', '155', '59', '5.1', '2.3', '1', '4.1', '143.47');
INSERT INTO Food (foodID, foodName, category, size, caloricintake, carbohydrate, fiber, protein, fat, water) VALUES ('FD00061', 'Garlic', 'vegetables', '100', '143', '28', '2.7', '6.6', '0.4', '63.1');
INSERT INTO Food (foodID, foodName, category, size, caloricintake, carbohydrate, fiber, protein, fat, water) VALUES ('FD00062', 'Green Beans', 'vegetables', '100', '31', '7', '2.7', '1.8', '0.2', '90.32');
INSERT INTO Food (foodID, foodName, category, size, caloricintake, carbohydrate, fiber, protein, fat, water) VALUES ('FD00063', 'Greens', 'vegetables', '145', '117', '21', '8.3', '7.9', '0.6', '114.35');
INSERT INTO Food (foodID, foodName, category, size, caloricintake, carbohydrate, fiber, protein, fat, water) VALUES ('FD00064', 'Collard Greens', 'vegetables', '85', '30', '5', '3', '3', '0.1', '50');
INSERT INTO Food (foodID, foodName, category, size, caloricintake, carbohydrate, fiber, protein, fat, water) VALUES ('FD00065', 'Mustard Greens', 'vegetables', '56', '15', '2.6', '1.8', '1.6', '0.2', '50.79');
INSERT INTO Food (foodID, foodName, category, size, caloricintake, carbohydrate, fiber, protein, fat, water) VALUES ('FD00066', 'Gourds', 'vegetables', '95', '19', '4.1', '1.1', '1.1', '0.2', '89.16');
INSERT INTO Food (foodID, foodName, category, size, caloricintake, carbohydrate, fiber, protein, fat, water) VALUES ('FD00067', 'Jicama', 'vegetables', '130', '49', '11', '6.4', '0.9', '0.1', '117.09');
INSERT INTO Food (foodID, foodName, category, size, caloricintake, carbohydrate, fiber, protein, fat, water) VALUES ('FD00068', 'Kale', 'vegetables', '21', '7', '0.9', '0.9', '0.6', '0.3', '18.82');
INSERT INTO Food (foodID, foodName, category, size, caloricintake, carbohydrate, fiber, protein, fat, water) VALUES ('FD00069', 'Kohlrabi', 'vegetables', '135', '36', '8.4', '4.9', '2.3', '0.1', '122.85');
INSERT INTO Food (foodID, foodName, category, size, caloricintake, carbohydrate, fiber, protein, fat, water) VALUES ('FD00070', 'Leeks', 'vegetables', '90', '55', '13', '1.6', '1.4', '0.3', '74.7');
INSERT INTO Food (foodID, foodName, category, size, caloricintake, carbohydrate, fiber, protein, fat, water) VALUES ('FD00071', 'Arugula Lettuce', 'vegetables', '20', '5', '0.7', '0.3', '0.5', '0.1', '18.34');
INSERT INTO Food (foodID, foodName, category, size, caloricintake, carbohydrate, fiber, protein, fat, water) VALUES ('FD00072', 'Butter Lettuce', 'vegetables', '85', '10', '2', '1', '1', '0', '30');
INSERT INTO Food (foodID, foodName, category, size, caloricintake, carbohydrate, fiber, protein, fat, water) VALUES ('FD00073', 'Endive Lettuce', 'vegetables', '85', '20', '3', '2', '1', '0', '50');
INSERT INTO Food (foodID, foodName, category, size, caloricintake, carbohydrate, fiber, protein, fat, water) VALUES ('FD00074', 'Green and Red Leaf Lettuce', 'vegetables', '85', '10', '2', '1', '1', '0', '42');
INSERT INTO Food (foodID, foodName, category, size, caloricintake, carbohydrate, fiber, protein, fat, water) VALUES ('FD00075', 'Romaine Lettuce', 'vegetables', '35', '5', '1', '0.5', '0.5', '0.1', '33.24');
INSERT INTO Food (foodID, foodName, category, size, caloricintake, carbohydrate, fiber, protein, fat, water) VALUES ('FD00076', 'Lima Beans', 'vegetables', '156', '176', '31', '7.6', '11', '1.3', '109.57');
INSERT INTO Food (foodID, foodName, category, size, caloricintake, carbohydrate, fiber, protein, fat, water) VALUES ('FD00077', 'Mushrooms', 'vegetables', '70', '15', '2.3', '0.7', '2.2', '0.2', '64.72');
INSERT INTO Food (foodID, foodName, category, size, caloricintake, carbohydrate, fiber, protein, fat, water) VALUES ('FD00078', 'Okra', 'vegetables', '100', '33', '7.5', '3.2', '1.9', '0.2', '89.58');
INSERT INTO Food (foodID, foodName, category, size, caloricintake, carbohydrate, fiber, protein, fat, water) VALUES ('FD00079', 'Onions', 'vegetables', '160', '64', '15', '2.7', '1.8', '0.2', '142.58');
INSERT INTO Food (foodID, foodName, category, size, caloricintake, carbohydrate, fiber, protein, fat, water) VALUES ('FD00080', 'Green Onions', 'vegetables', '100', '32', '7.3', '2.6', '1.8', '0.2', '276');
INSERT INTO Food (foodID, foodName, category, size, caloricintake, carbohydrate, fiber, protein, fat, water) VALUES ('FD00081', 'Parsnips', 'vegetables', '133', '100', '24', '6.5', '1.6', '0.4', '105.77');
INSERT INTO Food (foodID, foodName, category, size, caloricintake, carbohydrate, fiber, protein, fat, water) VALUES ('FD00082', 'Peas', 'vegetables', '125', '71', '19', '3.9', '12', '0.2', '104.95');
INSERT INTO Food (foodID, foodName, category, size, caloricintake, carbohydrate, fiber, protein, fat, water) VALUES ('FD00083', 'Snap Sugar Peas', 'vegetables', '85', '35', '6', '2', '2', '0', '50');
INSERT INTO Food (foodID, foodName, category, size, caloricintake, carbohydrate, fiber, protein, fat, water) VALUES ('FD00084', 'Snow Peas', 'vegetables', '85', '33', '5', '1.5', '2.2', '0.2', '43');
INSERT INTO Food (foodID, foodName, category, size, caloricintake, carbohydrate, fiber, protein, fat, water) VALUES ('FD00085', 'Anaheim Peppers', 'vegetables', '284', '199', '25', '4', '16', '4.5', '100');
INSERT INTO Food (foodID, foodName, category, size, caloricintake, carbohydrate, fiber, protein, fat, water) VALUES ('FD00086', 'Sweet peppers', 'vegetables', '150', '39', '9', '3.2', '1.5', '0.5', '138.31');
INSERT INTO Food (foodID, foodName, category, size, caloricintake, carbohydrate, fiber, protein, fat, water) VALUES ('FD00087', 'Potatoes', 'vegetables', '100', '58', '12', '2.5', '2.6', '0.1', '83.29');
INSERT INTO Food (foodID, foodName, category, size, caloricintake, carbohydrate, fiber, protein, fat, water) VALUES ('FD00088', 'Pumpkin', 'vegetables', '116', '30', '7.5', '0.6', '1.2', '0.1', '106.26');
INSERT INTO Food (foodID, foodName, category, size, caloricintake, carbohydrate, fiber, protein, fat, water) VALUES ('FD00089', 'Radicchio', 'vegetables', '40', '9', '1.8', '0.4', '0.6', '0.1', '37.26');
INSERT INTO Food (foodID, foodName, category, size, caloricintake, carbohydrate, fiber, protein, fat, water) VALUES ('FD00090', 'Radish', 'vegetables', '115', '18', '3.9', '1.8', '0.8', '0.1', '109.56');
INSERT INTO Food (foodID, foodName, category, size, caloricintake, carbohydrate, fiber, protein, fat, water) VALUES ('FD00091', 'Rhubarb', 'vegetables', '240', '170', '42', '3.8', '1.9', '0.5', '193.99');
INSERT INTO Food (foodID, foodName, category, size, caloricintake, carbohydrate, fiber, protein, fat, water) VALUES ('FD00092', 'Romanesco (cauliflower)', 'vegetables', '100', '25', '7', '1', '0.9', '0.2', '70.23');
INSERT INTO Food (foodID, foodName, category, size, caloricintake, carbohydrate, fiber, protein, fat, water) VALUES ('FD00093', 'Rutabaga', 'vegetables', '140', '52', '12', '3.2', '1.5', '0.2', '25.2');
INSERT INTO Food (foodID, foodName, category, size, caloricintake, carbohydrate, fiber, protein, fat, water) VALUES ('FD00094', 'Shallots', 'vegetables', '10', '7', '1.7', '0.3', '0.3', '0', '7.98');
INSERT INTO Food (foodID, foodName, category, size, caloricintake, carbohydrate, fiber, protein, fat, water) VALUES ('FD00095', 'Spinach', 'vegetables', '30', '6', '1.1', '0.7', '0.9', '0.1', '27.42');
INSERT INTO Food (foodID, foodName, category, size, caloricintake, carbohydrate, fiber, protein, fat, water) VALUES ('FD00096', 'Squash', 'vegetables', '140', '56', '15', '2.1', '1.1', '0.1', '122.89');
INSERT INTO Food (foodID, foodName, category, size, caloricintake, carbohydrate, fiber, protein, fat, water) VALUES ('FD00097', 'Acorn Squash', 'vegetables', '140', '56', '15', '2.1', '1.1', '0.1', '122.89');
INSERT INTO Food (foodID, foodName, category, size, caloricintake, carbohydrate, fiber, protein, fat, water) VALUES ('FD00098', 'Butternut Squash', 'vegetables', '85', '45', '10', '2', '1', '0', '');
INSERT INTO Food (foodID, foodName, category, size, caloricintake, carbohydrate, fiber, protein, fat, water) VALUES ('FD00099', 'Patty Pan Squash', 'vegetables', '100', '18', '3.84', '1.2', '1.2', '0.2', '52.17');
INSERT INTO Food (foodID, foodName, category, size, caloricintake, carbohydrate, fiber, protein, fat, water) VALUES ('FD00100', 'Spaghetti Squash', 'vegetables', '101', '31', '7', '1.5', '0.7', '0.6', '92.52');
INSERT INTO Food (foodID, foodName, category, size, caloricintake, carbohydrate, fiber, protein, fat, water) VALUES ('FD00101', 'Sweet Potato', 'vegetables', '34', '11', '2', '0.7', '0.3', '0.3', '31.15');
INSERT INTO Food (foodID, foodName, category, size, caloricintake, carbohydrate, fiber, protein, fat, water) VALUES ('FD00102', 'Tomatillo', 'vegetables', '34', '11', '2', '0.7', '0.3', '0.3', '31.15');
INSERT INTO Food (foodID, foodName, category, size, caloricintake, carbohydrate, fiber, protein, fat, water) VALUES ('FD00103', 'Tomatoes', 'vegetables', '180', '32', '7', '2.2', '1.6', '0.4', '170.14');
INSERT INTO Food (foodID, foodName, category, size, caloricintake, carbohydrate, fiber, protein, fat, water) VALUES ('FD00104', 'Turnips', 'vegetables', '130', '36', '8.4', '2.3', '1.2', '0.1', '119.43');
INSERT INTO Food (foodID, foodName, category, size, caloricintake, carbohydrate, fiber, protein, fat, water) VALUES ('FD00105', 'Water Chestnuts', 'vegetables', '2', '45', '9', '3', '1', '0', '');
INSERT INTO Food (foodID, foodName, category, size, caloricintake, carbohydrate, fiber, protein, fat, water) VALUES ('FD00106', 'Yam', 'vegetables', '150', '177', '42', '6.2', '2.3', '0.3', '104.4');
INSERT INTO Food (foodID, foodName, category, size, caloricintake, carbohydrate, fiber, protein, fat, water) VALUES ('FD00107', 'Zucchini', 'vegetables', '10', '30', '4.2', '0.1', '0.5', '1.3', '3.79');
INSERT INTO Food (foodID, foodName, category, size, caloricintake, carbohydrate, fiber, protein, fat, water) VALUES ('FD00108', 'Tuna', 'fish', '28', '31', '0', '0', '6.9', '0.1', '20.99');
INSERT INTO Food (foodID, foodName, category, size, caloricintake, carbohydrate, fiber, protein, fat, water) VALUES ('FD00109', 'Salmon', 'fish', '166', '211', '0', '0', '34', '7.3', '125.36');
INSERT INTO Food (foodID, foodName, category, size, caloricintake, carbohydrate, fiber, protein, fat, water) VALUES ('FD00110', 'Cod', 'fish', '136', '118', '0', '0', '26', '0.7', '107.43');
INSERT INTO Food (foodID, foodName, category, size, caloricintake, carbohydrate, fiber, protein, fat, water) VALUES ('FD00111', 'Alaskan pollock', 'fish', '85', '65', '0', '0', '15', '0.7', '153.46');
INSERT INTO Food (foodID, foodName, category, size, caloricintake, carbohydrate, fiber, protein, fat, water) VALUES ('FD00112', 'Trout', 'fish', '136', '241', '0', '0', '34', '11', '90.06');
INSERT INTO Food (foodID, foodName, category, size, caloricintake, carbohydrate, fiber, protein, fat, water) VALUES ('FD00113', 'Bass', 'fish', '28', '45', '1.1', '0.2', '3.1', '3', '20.36');
INSERT INTO Food (foodID, foodName, category, size, caloricintake, carbohydrate, fiber, protein, fat, water) VALUES ('FD00114', 'Anchovies', 'fish', '28', '60', '0', '0', '8.2', '2.8', '14.26');
INSERT INTO Food (foodID, foodName, category, size, caloricintake, carbohydrate, fiber, protein, fat, water) VALUES ('FD00115', 'Halibut', 'fish', '28', '26', '0', '0', '5.3', '0.4', '22.78');
INSERT INTO Food (foodID, foodName, category, size, caloricintake, carbohydrate, fiber, protein, fat, water) VALUES ('FD00116', 'Sardines', 'fish', '28', '115', '0', '0', '13', '6.6', '8.03');
INSERT INTO Food (foodID, foodName, category, size, caloricintake, carbohydrate, fiber, protein, fat, water) VALUES ('FD00117', 'Black carp', 'fish', '85', '108', '0', '0', '15', '4.8', '64.86');
INSERT INTO Food (foodID, foodName, category, size, caloricintake, carbohydrate, fiber, protein, fat, water) VALUES ('FD00118', 'Snakehead fish', 'fish', '100', '261', '22', '0', '38', '2.3', '26.4');
INSERT INTO Food (foodID, foodName, category, size, caloricintake, carbohydrate, fiber, protein, fat, water) VALUES ('FD00119', 'Crucian carp', 'fish', '85', '108', '0', '0', '15', '4.8', '64.86');
INSERT INTO Food (foodID, foodName, category, size, caloricintake, carbohydrate, fiber, protein, fat, water) VALUES ('FD00120', 'Catfish', 'fish', '136', '204', '0', '0', '26', '10', '99.06');
INSERT INTO Food (foodID, foodName, category, size, caloricintake, carbohydrate, fiber, protein, fat, water) VALUES ('FD00121', 'Perch fish', 'fish', '60', '55', '0', '0', '12', '0.6', '47.48');
INSERT INTO Food (foodID, foodName, category, size, caloricintake, carbohydrate, fiber, protein, fat, water) VALUES ('FD00122', 'Silver carp', 'fish', '85', '108', '0', '0', '15', '4.8', '64.86');
INSERT INTO Food (foodID, foodName, category, size, caloricintake, carbohydrate, fiber, protein, fat, water) VALUES ('FD00123', 'Mackerel', 'fish', '28', '54', '0', '0', '5.4', '3.4', '18.63');
INSERT INTO Food (foodID, foodName, category, size, caloricintake, carbohydrate, fiber, protein, fat, water) VALUES ('FD00124', 'Pompano', 'fish', '28', '46', '0', '0', '5.2', '2.7', '20.16');
INSERT INTO Food (foodID, foodName, category, size, caloricintake, carbohydrate, fiber, protein, fat, water) VALUES ('FD00125', 'Herring', 'fish', '28', '45', '0', '0', '5.1', '2.6', '20.43');
INSERT INTO Food (foodID, foodName, category, size, caloricintake, carbohydrate, fiber, protein, fat, water) VALUES ('FD00126', 'Sturgeon', 'fish', '136', '180', '0', '0', '28', '6.9', '94.76');
INSERT INTO Food (foodID, foodName, category, size, caloricintake, carbohydrate, fiber, protein, fat, water) VALUES ('FD00127', 'Lobster', 'seafood', '145', '128', '0', '0', '27', '1.2', '112.52');
INSERT INTO Food (foodID, foodName, category, size, caloricintake, carbohydrate, fiber, protein, fat, water) VALUES ('FD00128', 'Crabs', 'seafood', '118', '97', '0', '0', '21', '0.9', '93.42');
INSERT INTO Food (foodID, foodName, category, size, caloricintake, carbohydrate, fiber, protein, fat, water) VALUES ('FD00129', 'Shrimps', 'seafood', '182', '360', '2.2', '0.7', '19', '30', '126.76');
INSERT INTO Food (foodID, foodName, category, size, caloricintake, carbohydrate, fiber, protein, fat, water) VALUES ('FD00130', 'Prawns', 'seafood', '112', '80', '1', '0', '15', '1', '0');
INSERT INTO Food (foodID, foodName, category, size, caloricintake, carbohydrate, fiber, protein, fat, water) VALUES ('FD00131', 'Crayfish', 'seafood', '140', '113', '0', '0', '23', '1.7', '110.39');
INSERT INTO Food (foodID, foodName, category, size, caloricintake, carbohydrate, fiber, protein, fat, water) VALUES ('FD00132', 'Clam', 'seafood', '227', '195', '8.1', '0', '33', '2.2', '179.28');
INSERT INTO Food (foodID, foodName, category, size, caloricintake, carbohydrate, fiber, protein, fat, water) VALUES ('FD00133', 'Snail', 'seafood', '85', '77', '1.7', '0', '14', '1.2', '67.32');
INSERT INTO Food (foodID, foodName, category, size, caloricintake, carbohydrate, fiber, protein, fat, water) VALUES ('FD00134', 'Abalone', 'seafood', '28', '59', '3.4', '0', '9.7', '0.4', '13.74');
INSERT INTO Food (foodID, foodName, category, size, caloricintake, carbohydrate, fiber, protein, fat, water) VALUES ('FD00135', 'Scallop', 'seafood', '180', '247', '11', '0', '43', '1.8', '115.81');
INSERT INTO Food (foodID, foodName, category, size, caloricintake, carbohydrate, fiber, protein, fat, water) VALUES ('FD00136', 'Limpet', 'seafood', '53', '40', '1', '0', '9', '0', '0');
INSERT INTO Food (foodID, foodName, category, size, caloricintake, carbohydrate, fiber, protein, fat, water) VALUES ('FD00137', 'Squids', 'seafood', '28', '26', '0.9', '0', '4.4', '0.4', '22.27');
INSERT INTO Food (foodID, foodName, category, size, caloricintake, carbohydrate, fiber, protein, fat, water) VALUES ('FD00138', 'Octopus', 'seafood', '28', '46', '1.2', '0', '8.4', '0.6', '17.04');
INSERT INTO Food (foodID, foodName, category, size, caloricintake, carbohydrate, fiber, protein, fat, water) VALUES ('FD00139', 'Jellyfish', 'seafood', '58', '21', '0', '0', '3.2', '0.8', '39.44');
INSERT INTO Food (foodID, foodName, category, size, caloricintake, carbohydrate, fiber, protein, fat, water) VALUES ('FD00140', 'Frogs', 'seafood', '40', '120', '29', '0', '2', '0', '0');
INSERT INTO Food (foodID, foodName, category, size, caloricintake, carbohydrate, fiber, protein, fat, water) VALUES ('FD00141', 'Urchins', 'seafood', '100', '120', '3', '0', '16', '5', '0');
INSERT INTO Food (foodID, foodName, category, size, caloricintake, carbohydrate, fiber, protein, fat, water) VALUES ('FD00142', 'Sea cucumber', 'seafood', '100', '56', '0', '0', '13', '0.4', '80.7');
INSERT INTO Food (foodID, foodName, category, size, caloricintake, carbohydrate, fiber, protein, fat, water) VALUES ('FD00143', 'Oyster', 'seafood', '248', '126', '6.8', '0', '14', '4.2', '220.82');
INSERT INTO Food (foodID, foodName, category, size, caloricintake, carbohydrate, fiber, protein, fat, water) VALUES ('FD00144', 'Mussels', 'seafood', '150', '129', '5.5', '0', '18', '3.4', '120.87');
INSERT INTO Food (foodID, foodName, category, size, caloricintake, carbohydrate, fiber, protein, fat, water) VALUES ('FD00145', 'Beef', 'meat', '100', '268', '0', '0', '25', '18', '61');
INSERT INTO Food (foodID, foodName, category, size, caloricintake, carbohydrate, fiber, protein, fat, water) VALUES ('FD00146', 'Lamb', 'meat', '28', '80', '0', '0', '4.7', '6.6', '16.86');
INSERT INTO Food (foodID, foodName, category, size, caloricintake, carbohydrate, fiber, protein, fat, water) VALUES ('FD00147', 'Veal', 'meat', '85', '167', '0', '0', '16', '11', '56.24');
INSERT INTO Food (foodID, foodName, category, size, caloricintake, carbohydrate, fiber, protein, fat, water) VALUES ('FD00148', 'Pork', 'meat', '28', '75', '0', '0', '4.8', '6', '17.31');
INSERT INTO Food (foodID, foodName, category, size, caloricintake, carbohydrate, fiber, protein, fat, water) VALUES ('FD00149', 'Kangaroo', 'meat', '85', '125', '0', '0', '22', '3.4', '0');
INSERT INTO Food (foodID, foodName, category, size, caloricintake, carbohydrate, fiber, protein, fat, water) VALUES ('FD00150', 'Ham', 'meat', '182', '419', '5', '0.7', '24', '33', '114.66');
INSERT INTO Food (foodID, foodName, category, size, caloricintake, carbohydrate, fiber, protein, fat, water) VALUES ('FD00151', 'Sausages', 'meat', '57', '88', '0.3', '0', '11', '4.6', '40.14');
INSERT INTO Food (foodID, foodName, category, size, caloricintake, carbohydrate, fiber, protein, fat, water) VALUES ('FD00152', 'Chicken', 'poultry', '85', '128', '0', '0', '26', '2.7', '0');
INSERT INTO Food (foodID, foodName, category, size, caloricintake, carbohydrate, fiber, protein, fat, water) VALUES ('FD00153', 'Turkey', 'poultry', '113', '167', '0', '0', '22', '8.7', '81.77');
INSERT INTO Food (foodID, foodName, category, size, caloricintake, carbohydrate, fiber, protein, fat, water) VALUES ('FD00154', 'Duck', 'poultry', '137', '185', '1.3', '0', '25', '8.2', '101.06');
INSERT INTO Food (foodID, foodName, category, size, caloricintake, carbohydrate, fiber, protein, fat, water) VALUES ('FD00155', 'Quail', 'poultry', '92', '123', '0', '0', '20', '1.2', '64.63');
INSERT INTO Food (foodID, foodName, category, size, caloricintake, carbohydrate, fiber, protein, fat, water) VALUES ('FD00156', 'Pigeon', 'poultry', '251', '356', '0', '0', '44', '19', '182.73');
INSERT INTO Food (foodID, foodName, category, size, caloricintake, carbohydrate, fiber, protein, fat, water) VALUES ('FD00157', 'Chicken eggs', 'egg', '50', '72', '0.4', '0', '6.3', '4.8', '0');
INSERT INTO Food (foodID, foodName, category, size, caloricintake, carbohydrate, fiber, protein, fat, water) VALUES ('FD00158', 'Duck eggs', 'egg', '135', '301', '1.8', '0', '16', '25', '90.11');
INSERT INTO Food (foodID, foodName, category, size, caloricintake, carbohydrate, fiber, protein, fat, water) VALUES ('FD00159', 'Quail eggs', 'egg', '9', '14', '0', '0', '1.2', '1', '6.67');
INSERT INTO Food (foodID, foodName, category, size, caloricintake, carbohydrate, fiber, protein, fat, water) VALUES ('FD00160', 'Fish eggs', 'egg', '100', '104', '4.9', '0', '15', '2.9', '76.24');
INSERT INTO Food (foodID, foodName, category, size, caloricintake, carbohydrate, fiber, protein, fat, water) VALUES ('FD00161', 'Almond', 'nuts', '141', '856', '29', '15', '29', '76', '3.3');
INSERT INTO Food (foodID, foodName, category, size, caloricintake, carbohydrate, fiber, protein, fat, water) VALUES ('FD00162', 'Pine nut', 'nuts', '30', '200', '4', '1', '4', '21', '3.2');
INSERT INTO Food (foodID, foodName, category, size, caloricintake, carbohydrate, fiber, protein, fat, water) VALUES ('FD00163', 'Walnut', 'nuts', '117', '765', '16', '7.8', '18', '76', '4.76');
INSERT INTO Food (foodID, foodName, category, size, caloricintake, carbohydrate, fiber, protein, fat, water) VALUES ('FD00164', 'Macadamia', 'nuts', '132', '945', '17', '11', '10', '100', '2.13');
INSERT INTO Food (foodID, foodName, category, size, caloricintake, carbohydrate, fiber, protein, fat, water) VALUES ('FD00165', 'Hazelnut', 'nuts', '135', '848', '23', '13', '20', '82', '7.17');
INSERT INTO Food (foodID, foodName, category, size, caloricintake, carbohydrate, fiber, protein, fat, water) VALUES ('FD00166', 'Cashew', 'nuts', '160', '28', '8', '1', '5', '14', '5.15');
INSERT INTO Food (foodID, foodName, category, size, caloricintake, carbohydrate, fiber, protein, fat, water) VALUES ('FD00167', 'Peanut', 'nuts', '146', '832', '23', '14', '38', '72', '9.33');
INSERT INTO Food (foodID, foodName, category, size, caloricintake, carbohydrate, fiber, protein, fat, water) VALUES ('FD00168', 'watermelon seed', 'nuts', '108', '602', '17', '8', '31', '51', '5.45');
INSERT INTO Food (foodID, foodName, category, size, caloricintake, carbohydrate, fiber, protein, fat, water) VALUES ('FD00169', 'pumpkin seeds', 'nuts', '46', '264', '6.8', '3', '14', '23', '0.93');
INSERT INTO Food (foodID, foodName, category, size, caloricintake, carbohydrate, fiber, protein, fat, water) VALUES ('FD00170', 'sesame seeds', 'nuts', '128', '808', '15', '14', '26', '78', '4.8');
INSERT INTO Food (foodID, foodName, category, size, caloricintake, carbohydrate, fiber, protein, fat, water) VALUES ('FD00171', 'sunflower seeds', 'nuts', '28', '160', '5', '3', '6', '14', '4.5');
INSERT INTO Food (foodID, foodName, category, size, caloricintake, carbohydrate, fiber, protein, fat, water) VALUES ('FD00172', 'Brazilnuts', 'nuts', '133', '876', '16', '10', '19', '89', '4.55');
INSERT INTO Food (foodID, foodName, category, size, caloricintake, carbohydrate, fiber, protein, fat, water) VALUES ('FD00173', 'All beans', 'legumes', '184', '613', '110', '46', '43', '1.5', '21.62');
INSERT INTO Food (foodID, foodName, category, size, caloricintake, carbohydrate, fiber, protein, fat, water) VALUES ('FD00174', 'Lentils', 'legumes', '192', '676', '122', '21', '47', '2', '15.86');
INSERT INTO Food (foodID, foodName, category, size, caloricintake, carbohydrate, fiber, protein, fat, water) VALUES ('FD00175', 'Chickpeas', 'legumes', '185', '389', '47', '13', '15', '16', '103.53');
INSERT INTO Food (foodID, foodName, category, size, caloricintake, carbohydrate, fiber, protein, fat, water) VALUES ('FD00176', 'Split peas', 'legumes', '180', '211', '38', '15', '15', '0.7', '124.34');
INSERT INTO Food (foodID, foodName, category, size, caloricintake, carbohydrate, fiber, protein, fat, water) VALUES ('FD00177', 'Tofu', 'legumes', '28', '77', '2.5', '1.1', '5.3', '5.7', '14.32');
INSERT INTO Food (foodID, foodName, category, size, caloricintake, carbohydrate, fiber, protein, fat, water) VALUES ('FD00178', 'Bread', 'starch', '28', '81', '14', '0.7', '2.7', '1.7', '9.84');
INSERT INTO Food (foodID, foodName, category, size, caloricintake, carbohydrate, fiber, protein, fat, water) VALUES ('FD00179', 'Spaghetti', 'starch', '140', '220', '43', '2.5', '8.1', '1.3', '54.58');
INSERT INTO Food (foodID, foodName, category, size, caloricintake, carbohydrate, fiber, protein, fat, water) VALUES ('FD00180', 'Rice', 'starch', '100', '130', '28.7', '0', '2.36', '0.19', '0');
INSERT INTO Food (foodID, foodName, category, size, caloricintake, carbohydrate, fiber, protein, fat, water) VALUES ('FD00181', 'Pie', 'starch', '172', '874', '97', '5.7', '11', '49', '12.35');
INSERT INTO Food (foodID, foodName, category, size, caloricintake, carbohydrate, fiber, protein, fat, water) VALUES ('FD00182', 'Sandwiches', 'starch', '29', '77', '14', '0.8', '2.6', '1', '15.85');
INSERT INTO Food (foodID, foodName, category, size, caloricintake, carbohydrate, fiber, protein, fat, water) VALUES ('FD00183', 'Pasta', 'starch', '140', '220', '43', '2.5', '8.1', '1.3', '86.46');
INSERT INTO Food (foodID, foodName, category, size, caloricintake, carbohydrate, fiber, protein, fat, water) VALUES ('FD00184', 'Tacos shell', 'starch', '28', '133', '18', '1.9', '1.8', '6.1', '1.79');
INSERT INTO Food (foodID, foodName, category, size, caloricintake, carbohydrate, fiber, protein, fat, water) VALUES ('FD00185', 'Cereal Granola', 'dairies&dessert', '111', '486', '82', '10', '11', '13', '3.33');
INSERT INTO Food (foodID, foodName, category, size, caloricintake, carbohydrate, fiber, protein, fat, water) VALUES ('FD00186', 'Oatmeal', 'dairies&dessert', '238', '479', '61', '11', '16', '20', '130.8');
INSERT INTO Food (foodID, foodName, category, size, caloricintake, carbohydrate, fiber, protein, fat, water) VALUES ('FD00187', 'Milk', 'dairies&dessert', '244', '146', '11', '0', '8', '7.8', '214.96');
INSERT INTO Food (foodID, foodName, category, size, caloricintake, carbohydrate, fiber, protein, fat, water) VALUES ('FD00188', 'Yogurt', 'dairies&dessert', '245', '230', '39', '0.5', '8.6', '4.4', '189.88');
INSERT INTO Food (foodID, foodName, category, size, caloricintake, carbohydrate, fiber, protein, fat, water) VALUES ('FD00189', 'Cheese', 'dairies&dessert', '15', '24', '1.2', '0', '0.5', '2', '11.12');
INSERT INTO Food (foodID, foodName, category, size, caloricintake, carbohydrate, fiber, protein, fat, water) VALUES ('FD00190', 'Soy milk', 'dairies&dessert', '244', '105', '12', '0.5', '6.3', '3.6', '220.48');
INSERT INTO Food (foodID, foodName, category, size, caloricintake, carbohydrate, fiber, protein, fat, water) VALUES ('FD00191', 'Whipped cream', 'dairies&dessert', '40', '137', '3.4', '0', '1.1', '14', '21.72');
INSERT INTO Food (foodID, foodName, category, size, caloricintake, carbohydrate, fiber, protein, fat, water) VALUES ('FD00192', 'Ice cream', 'dairies&dessert', '132', '273', '31', '0.9', '4.6', '15', '0');
INSERT INTO Food (foodID, foodName, category, size, caloricintake, carbohydrate, fiber, protein, fat, water) VALUES ('FD00193', 'Gelato', 'dairies&dessert', '132', '273', '31', '0.9', '4.6', '15', '0');
INSERT INTO Food (foodID, foodName, category, size, caloricintake, carbohydrate, fiber, protein, fat, water) VALUES ('FD00194', 'Sherbet', 'dairies&dessert', '74', '107', '23', '1', '0.8', '1.5', '48.91');
INSERT INTO Food (foodID, foodName, category, size, caloricintake, carbohydrate, fiber, protein, fat, water) VALUES ('FD00195', 'Kefir', 'dairies&dessert', '244', '127', '18', '0', '8.8', '2.3', '212.91');
INSERT INTO Food (foodID, foodName, category, size, caloricintake, carbohydrate, fiber, protein, fat, water) VALUES ('FD00196', 'Soft cheese', 'dairies&dessert', '15', '51', '0.8', '0', '0.9', '5', '0');
INSERT INTO Food (foodID, foodName, category, size, caloricintake, carbohydrate, fiber, protein, fat, water) VALUES ('FD00197', 'Brownies', 'dairies&dessert', '99', '410', '50', '5.1', '6', '25', '0');
INSERT INTO Food (foodID, foodName, category, size, caloricintake, carbohydrate, fiber, protein, fat, water) VALUES ('FD00198', 'Cookies', 'dairies&dessert', '45', '231', '29', '0.6', '2.4', '12', '1.62');
INSERT INTO Food (foodID, foodName, category, size, caloricintake, carbohydrate, fiber, protein, fat, water) VALUES ('FD00199', 'Pudding', 'dairies&dessert', '260', '281', '48', '0.8', '8.4', '5.6', '195.39');
INSERT INTO Food (foodID, foodName, category, size, caloricintake, carbohydrate, fiber, protein, fat, water) VALUES ('FD00200', 'Cake', 'dairies&dessert', '4', '11', '1.5', '0', '0.2', '0.5', '1.77');
INSERT INTO Food (foodID, foodName, category, size, caloricintake, carbohydrate, fiber, protein, fat, water) VALUES ('FD00201', 'Mousse', 'dairies&dessert', '170', '355', '28', '1', '7.4', '25', '108.14');
INSERT INTO Food (foodID, foodName, category, size, caloricintake, carbohydrate, fiber, protein, fat, water) VALUES ('FD00202', 'Water', 'drinks', '240', '0', '0', '0', '0', '0', '239.76');
INSERT INTO Food (foodID, foodName, category, size, caloricintake, carbohydrate, fiber, protein, fat, water) VALUES ('FD00203', 'Tea', 'drinks', '237', '2', '0.7', '0', '0', '0', '236');
INSERT INTO Food (foodID, foodName, category, size, caloricintake, carbohydrate, fiber, protein, fat, water) VALUES ('FD00204', 'Milk', 'drinks', '244', '146', '11', '0', '8', '7.8', '214.96');
INSERT INTO Food (foodID, foodName, category, size, caloricintake, carbohydrate, fiber, protein, fat, water) VALUES ('FD00205', 'Orange juice', 'drinks', '248', '112', '26', '0.5', '1.7', '0.5', '218.98');
INSERT INTO Food (foodID, foodName, category, size, caloricintake, carbohydrate, fiber, protein, fat, water) VALUES ('FD00206', 'Coffee', 'drinks', '240', '2', '0', '0', '0.3', '0', '238.54');

--INSERT EXERCISE
INSERT INTO Exercise (exerciseID, exname, lowerweight, upperweight, calorexp) VALUES ('EX001', 'Cycling, 16-19km/h, light', '0', '58', '354');
INSERT INTO Exercise (exerciseID, exname, lowerweight, upperweight, calorexp) VALUES ('EX002', 'Cycling, 16-19km/h, light', '59', '70', '442');
INSERT INTO Exercise (exerciseID, exname, lowerweight, upperweight, calorexp) VALUES ('EX003', 'Cycling, 16-19km/h, light', '71', '80', '490');
INSERT INTO Exercise (exerciseID, exname, lowerweight, upperweight, calorexp) VALUES ('EX004', 'Cycling, 16-19km/h, light', '81', '150', '558');
INSERT INTO Exercise (exerciseID, exname, lowerweight, upperweight, calorexp) VALUES ('EX005', 'Weight lifting, light workout', '0', '58', '177');
INSERT INTO Exercise (exerciseID, exname, lowerweight, upperweight, calorexp) VALUES ('EX006', 'Weight lifting, light workout', '59', '70', '211');
INSERT INTO Exercise (exerciseID, exname, lowerweight, upperweight, calorexp) VALUES ('EX007', 'Weight lifting, light workout', '71', '80', '245');
INSERT INTO Exercise (exerciseID, exname, lowerweight, upperweight, calorexp) VALUES ('EX008', 'Weight lifting, light workout', '81', '150', '279');
INSERT INTO Exercise (exerciseID, exname, lowerweight, upperweight, calorexp) VALUES ('EX009', 'Aerobics, general', '0', '58', '384');
INSERT INTO Exercise (exerciseID, exname, lowerweight, upperweight, calorexp) VALUES ('EX010', 'Aerobics, general', '59', '70', '457');
INSERT INTO Exercise (exerciseID, exname, lowerweight, upperweight, calorexp) VALUES ('EX011', 'Aerobics, general', '71', '80', '531');
INSERT INTO Exercise (exerciseID, exname, lowerweight, upperweight, calorexp) VALUES ('EX012', 'Aerobics, general', '81', '150', '605');
INSERT INTO Exercise (exerciseID, exname, lowerweight, upperweight, calorexp) VALUES ('EX013', 'Running, 5 mph (12 minute mile)', '0', '58', '472');
INSERT INTO Exercise (exerciseID, exname, lowerweight, upperweight, calorexp) VALUES ('EX014', 'Running, 5 mph (12 minute mile)', '59', '70', '563');
INSERT INTO Exercise (exerciseID, exname, lowerweight, upperweight, calorexp) VALUES ('EX015', 'Running, 5 mph (12 minute mile)', '71', '80', '654');
INSERT INTO Exercise (exerciseID, exname, lowerweight, upperweight, calorexp) VALUES ('EX016', 'Running, 5 mph (12 minute mile)', '81', '150', '754');
INSERT INTO Exercise (exerciseID, exname, lowerweight, upperweight, calorexp) VALUES ('EX017', 'Badminton', '0', '58', '266');
INSERT INTO Exercise (exerciseID, exname, lowerweight, upperweight, calorexp) VALUES ('EX018', 'Badminton', '59', '70', '317');
INSERT INTO Exercise (exerciseID, exname, lowerweight, upperweight, calorexp) VALUES ('EX019', 'Badminton', '71', '80', '368');
INSERT INTO Exercise (exerciseID, exname, lowerweight, upperweight, calorexp) VALUES ('EX020', 'Badminton', '81', '150', '419');
INSERT INTO Exercise (exerciseID, exname, lowerweight, upperweight, calorexp) VALUES ('EX021', 'Playing basketball, non game', '0', '58', '354');
INSERT INTO Exercise (exerciseID, exname, lowerweight, upperweight, calorexp) VALUES ('EX022', 'Playing basketball, non game', '59', '70', '422');
INSERT INTO Exercise (exerciseID, exname, lowerweight, upperweight, calorexp) VALUES ('EX023', 'Playing basketball, non game', '71', '80', '490');
INSERT INTO Exercise (exerciseID, exname, lowerweight, upperweight, calorexp) VALUES ('EX024', 'Playing basketball, non game', '81', '150', '558');
INSERT INTO Exercise (exerciseID, exname, lowerweight, upperweight, calorexp) VALUES ('EX025', 'Boxing, punching bag', '0', '58', '354');
INSERT INTO Exercise (exerciseID, exname, lowerweight, upperweight, calorexp) VALUES ('EX026', 'Boxing, punching bag', '59', '70', '422');
INSERT INTO Exercise (exerciseID, exname, lowerweight, upperweight, calorexp) VALUES ('EX027', 'Boxing, punching bag', '71', '80', '490');
INSERT INTO Exercise (exerciseID, exname, lowerweight, upperweight, calorexp) VALUES ('EX028', 'Boxing, punching bag', '81', '150', '558');
INSERT INTO Exercise (exerciseID, exname, lowerweight, upperweight, calorexp) VALUES ('EX029', 'Jumping rope, slow', '0', '58', '472');
INSERT INTO Exercise (exerciseID, exname, lowerweight, upperweight, calorexp) VALUES ('EX030', 'Jumping rope, slow', '59', '70', '563');
INSERT INTO Exercise (exerciseID, exname, lowerweight, upperweight, calorexp) VALUES ('EX031', 'Jumping rope, slow', '71', '80', '654');
INSERT INTO Exercise (exerciseID, exname, lowerweight, upperweight, calorexp) VALUES ('EX032', 'Jumping rope, slow', '81', '150', '745');
INSERT INTO Exercise (exerciseID, exname, lowerweight, upperweight, calorexp) VALUES ('EX033', 'Playing soccer', '0', '58', '413');
INSERT INTO Exercise (exerciseID, exname, lowerweight, upperweight, calorexp) VALUES ('EX034', 'Playing soccer', '59', '70', '493');
INSERT INTO Exercise (exerciseID, exname, lowerweight, upperweight, calorexp) VALUES ('EX035', 'Playing soccer', '71', '80', '572');
INSERT INTO Exercise (exerciseID, exname, lowerweight, upperweight, calorexp) VALUES ('EX036', 'Playing soccer', '81', '150', '651');
INSERT INTO Exercise (exerciseID, exname, lowerweight, upperweight, calorexp) VALUES ('EX037', 'Table tennis, ping pong', '0', '58', '236');
INSERT INTO Exercise (exerciseID, exname, lowerweight, upperweight, calorexp) VALUES ('EX038', 'Table tennis, ping pong', '59', '70', '281');
INSERT INTO Exercise (exerciseID, exname, lowerweight, upperweight, calorexp) VALUES ('EX039', 'Table tennis, ping pong', '71', '80', '327');
INSERT INTO Exercise (exerciseID, exname, lowerweight, upperweight, calorexp) VALUES ('EX040', 'Table tennis, ping pong', '81', '150', '372');
INSERT INTO Exercise (exerciseID, exname, lowerweight, upperweight, calorexp) VALUES ('EX041', 'Playing tennis', '0', '58', '413');
INSERT INTO Exercise (exerciseID, exname, lowerweight, upperweight, calorexp) VALUES ('EX042', 'Playing tennis', '59', '70', '493');
INSERT INTO Exercise (exerciseID, exname, lowerweight, upperweight, calorexp) VALUES ('EX043', 'Playing tennis', '71', '80', '573');
INSERT INTO Exercise (exerciseID, exname, lowerweight, upperweight, calorexp) VALUES ('EX044', 'Playing tennis', '81', '150', '651');
INSERT INTO Exercise (exerciseID, exname, lowerweight, upperweight, calorexp) VALUES ('EX045', 'Playing volleyball', '0', '58', '177');
INSERT INTO Exercise (exerciseID, exname, lowerweight, upperweight, calorexp) VALUES ('EX046', 'Playing volleyball', '59', '70', '211');
INSERT INTO Exercise (exerciseID, exname, lowerweight, upperweight, calorexp) VALUES ('EX047', 'Playing volleyball', '71', '80', '245');
INSERT INTO Exercise (exerciseID, exname, lowerweight, upperweight, calorexp) VALUES ('EX048', 'Playing volleyball', '81', '150', '279');
INSERT INTO Exercise (exerciseID, exname, lowerweight, upperweight, calorexp) VALUES ('EX049', 'Walking 2.0 mph, slow', '0', '58', '148');
INSERT INTO Exercise (exerciseID, exname, lowerweight, upperweight, calorexp) VALUES ('EX050', 'Walking 2.0 mph, slow', '59', '70', '176');
INSERT INTO Exercise (exerciseID, exname, lowerweight, upperweight, calorexp) VALUES ('EX051', 'Walking 2.0 mph, slow', '71', '80', '204');
INSERT INTO Exercise (exerciseID, exname, lowerweight, upperweight, calorexp) VALUES ('EX052', 'Walking 2.0 mph, slow', '81', '150', '233');
INSERT INTO Exercise (exerciseID, exname, lowerweight, upperweight, calorexp) VALUES ('EX053', 'Swimming freestyle, slow', '0', '58', '413');
INSERT INTO Exercise (exerciseID, exname, lowerweight, upperweight, calorexp) VALUES ('EX054', 'Swimming freestyle, slow', '59', '70', '493');
INSERT INTO Exercise (exerciseID, exname, lowerweight, upperweight, calorexp) VALUES ('EX055', 'Swimming freestyle, slow', '71', '80', '572');
INSERT INTO Exercise (exerciseID, exname, lowerweight, upperweight, calorexp) VALUES ('EX056', 'Swimming freestyle, slow', '81', '150', '651');

--INSERT IMAGE
INSERT INTO Image (imageID, productID, foodID, commentID, url) VALUES ('IMG000001', NULL, 'FD00001', NULL, 'https://images2.imgbox.com/5d/d0/Z6Cb8h4v_o.jpg');
INSERT INTO Image (imageID, productID, foodID, commentID, url) VALUES ('IMG000002', NULL, 'FD00002', NULL, 'https://images2.imgbox.com/e3/7f/AUKlSQGc_o.jpg');
INSERT INTO Image (imageID, productID, foodID, commentID, url) VALUES ('IMG000003', NULL, 'FD00003', NULL, 'https://images2.imgbox.com/22/f5/i6Jd29vu_o.jpg');
INSERT INTO Image (imageID, productID, foodID, commentID, url) VALUES ('IMG000004', NULL, 'FD00004', NULL, 'https://images2.imgbox.com/a4/95/vfpYzdZR_o.jpg');
INSERT INTO Image (imageID, productID, foodID, commentID, url) VALUES ('IMG000005', NULL, 'FD00005', NULL, 'https://images2.imgbox.com/f9/6c/YuGdA6B7_o.jpg');
INSERT INTO Image (imageID, productID, foodID, commentID, url) VALUES ('IMG000006', NULL, 'FD00006', NULL, 'https://images2.imgbox.com/76/d2/DlWyhMyS_o.jpg');
INSERT INTO Image (imageID, productID, foodID, commentID, url) VALUES ('IMG000007', NULL, 'FD00007', NULL, 'https://images2.imgbox.com/6e/ae/Vr9zvYvb_o.jpg');
INSERT INTO Image (imageID, productID, foodID, commentID, url) VALUES ('IMG000008', NULL, 'FD00008', NULL, 'https://images2.imgbox.com/49/cc/QlhGhUXd_o.jpg');
INSERT INTO Image (imageID, productID, foodID, commentID, url) VALUES ('IMG000009', NULL, 'FD00009', NULL, 'https://images2.imgbox.com/86/e0/dehHM2nh_o.jpg');
INSERT INTO Image (imageID, productID, foodID, commentID, url) VALUES ('IMG000010', NULL, 'FD00010', NULL, 'https://images2.imgbox.com/5b/47/B47cL078_o.jpg');
INSERT INTO Image (imageID, productID, foodID, commentID, url) VALUES ('IMG000011', NULL, 'FD00011', NULL, 'https://images2.imgbox.com/55/2f/prL4wuRU_o.jpg');
INSERT INTO Image (imageID, productID, foodID, commentID, url) VALUES ('IMG000012', NULL, 'FD00012', NULL, 'https://images2.imgbox.com/17/05/RjbuCa3h_o.jpg');
INSERT INTO Image (imageID, productID, foodID, commentID, url) VALUES ('IMG000013', NULL, 'FD00013', NULL, 'https://images2.imgbox.com/c8/b0/h6beRYH6_o.jpg');
INSERT INTO Image (imageID, productID, foodID, commentID, url) VALUES ('IMG000014', NULL, 'FD00014', NULL, 'https://images2.imgbox.com/51/3e/QDtqRqCb_o.jpg');
INSERT INTO Image (imageID, productID, foodID, commentID, url) VALUES ('IMG000015', NULL, 'FD00015', NULL, 'https://images2.imgbox.com/24/dd/pV5BAdhU_o.jpg');
INSERT INTO Image (imageID, productID, foodID, commentID, url) VALUES ('IMG000016', NULL, 'FD00016', NULL, 'https://images2.imgbox.com/ba/1d/VZJQBoBI_o.jpg');
INSERT INTO Image (imageID, productID, foodID, commentID, url) VALUES ('IMG000017', NULL, 'FD00017', NULL, 'https://images2.imgbox.com/ca/eb/KcFQX636_o.jpg');
INSERT INTO Image (imageID, productID, foodID, commentID, url) VALUES ('IMG000018', NULL, 'FD00018', NULL, 'https://images2.imgbox.com/a4/b3/q1fTcNjw_o.jpg');
INSERT INTO Image (imageID, productID, foodID, commentID, url) VALUES ('IMG000019', NULL, 'FD00019', NULL, 'https://images2.imgbox.com/28/bb/sVYvqNc6_o.jpg');
INSERT INTO Image (imageID, productID, foodID, commentID, url) VALUES ('IMG000020', NULL, 'FD00020', NULL, 'https://images2.imgbox.com/47/f6/MZ0PN0xW_o.jpg');
INSERT INTO Image (imageID, productID, foodID, commentID, url) VALUES ('IMG000021', NULL, 'FD00021', NULL, 'https://images2.imgbox.com/a8/57/cEhkoLrA_o.jpg');
INSERT INTO Image (imageID, productID, foodID, commentID, url) VALUES ('IMG000022', NULL, 'FD00022', NULL, 'https://images2.imgbox.com/28/b9/gAfIEqaD_o.jpg');
INSERT INTO Image (imageID, productID, foodID, commentID, url) VALUES ('IMG000023', NULL, 'FD00023', NULL, 'https://images2.imgbox.com/f4/58/4i1hZAtd_o.jpg');
INSERT INTO Image (imageID, productID, foodID, commentID, url) VALUES ('IMG000024', NULL, 'FD00024', NULL, 'https://images2.imgbox.com/e6/59/4D4kwwVB_o.jpg');
INSERT INTO Image (imageID, productID, foodID, commentID, url) VALUES ('IMG000025', NULL, 'FD00025', NULL, 'https://images2.imgbox.com/60/74/ZPG72zTf_o.jpg');
INSERT INTO Image (imageID, productID, foodID, commentID, url) VALUES ('IMG000026', NULL, 'FD00026', NULL, 'https://images2.imgbox.com/76/7a/hsZULsgA_o.jpg');
INSERT INTO Image (imageID, productID, foodID, commentID, url) VALUES ('IMG000027', NULL, 'FD00027', NULL, 'https://images2.imgbox.com/7c/98/guxLrNMF_o.jpg');
INSERT INTO Image (imageID, productID, foodID, commentID, url) VALUES ('IMG000028', NULL, 'FD00028', NULL, 'https://images2.imgbox.com/1d/3d/DYLtiVf5_o.jpg');
INSERT INTO Image (imageID, productID, foodID, commentID, url) VALUES ('IMG000029', NULL, 'FD00029', NULL, 'https://images2.imgbox.com/88/b2/DrfssFAK_o.jpg');
INSERT INTO Image (imageID, productID, foodID, commentID, url) VALUES ('IMG000030', NULL, 'FD00030', NULL, 'https://images2.imgbox.com/2e/8c/tuL04d2m_o.jpg');
INSERT INTO Image (imageID, productID, foodID, commentID, url) VALUES ('IMG000031', NULL, 'FD00031', NULL, 'https://images2.imgbox.com/47/c1/8HqWg1fg_o.jpg');
INSERT INTO Image (imageID, productID, foodID, commentID, url) VALUES ('IMG000032', NULL, 'FD00032', NULL, 'https://images2.imgbox.com/2a/1c/IUKKgsHh_o.jpg');
INSERT INTO Image (imageID, productID, foodID, commentID, url) VALUES ('IMG000033', NULL, 'FD00033', NULL, 'https://images2.imgbox.com/12/b0/SBNBlTKC_o.jpg');
INSERT INTO Image (imageID, productID, foodID, commentID, url) VALUES ('IMG000034', NULL, 'FD00034', NULL, 'https://images2.imgbox.com/19/12/BGDq6Yb3_o.jpg');
INSERT INTO Image (imageID, productID, foodID, commentID, url) VALUES ('IMG000035', NULL, 'FD00035', NULL, 'https://images2.imgbox.com/c8/96/YIOGgfkL_o.jpg');
INSERT INTO Image (imageID, productID, foodID, commentID, url) VALUES ('IMG000036', NULL, 'FD00036', NULL, 'https://images2.imgbox.com/62/80/DFZ2pX8J_o.jpg');
INSERT INTO Image (imageID, productID, foodID, commentID, url) VALUES ('IMG000037', NULL, 'FD00037', NULL, 'https://images2.imgbox.com/90/e8/ZbLTutgJ_o.jpg');
INSERT INTO Image (imageID, productID, foodID, commentID, url) VALUES ('IMG000038', NULL, 'FD00038', NULL, 'https://images2.imgbox.com/91/45/nF5RGwbt_o.jpg');
INSERT INTO Image (imageID, productID, foodID, commentID, url) VALUES ('IMG000039', NULL, 'FD00039', NULL, 'https://images2.imgbox.com/57/93/lTNo0FbS_o.jpg');
INSERT INTO Image (imageID, productID, foodID, commentID, url) VALUES ('IMG000040', NULL, 'FD00040', NULL, 'https://images2.imgbox.com/4b/99/5u88lK9R_o.jpg');
INSERT INTO Image (imageID, productID, foodID, commentID, url) VALUES ('IMG000041', NULL, 'FD00041', NULL, 'https://images2.imgbox.com/91/ab/lxYUUNAk_o.jpg');
INSERT INTO Image (imageID, productID, foodID, commentID, url) VALUES ('IMG000042', NULL, 'FD00042', NULL, 'https://images2.imgbox.com/62/82/D0zwVCC5_o.jpg');
INSERT INTO Image (imageID, productID, foodID, commentID, url) VALUES ('IMG000043', NULL, 'FD00043', NULL, 'https://images2.imgbox.com/b4/a3/2fNdUBlF_o.jpg');
INSERT INTO Image (imageID, productID, foodID, commentID, url) VALUES ('IMG000044', NULL, 'FD00044', NULL, 'https://images2.imgbox.com/b4/a3/2fNdUBlF_o.jpg');
INSERT INTO Image (imageID, productID, foodID, commentID, url) VALUES ('IMG000045', NULL, 'FD00045', NULL, 'https://images2.imgbox.com/4f/5b/i6ff2C1S_o.jpg');
INSERT INTO Image (imageID, productID, foodID, commentID, url) VALUES ('IMG000046', NULL, 'FD00046', NULL, 'https://images2.imgbox.com/c7/39/ypiRvqC7_o.jpg');
INSERT INTO Image (imageID, productID, foodID, commentID, url) VALUES ('IMG000047', NULL, 'FD00047', NULL, 'https://images2.imgbox.com/8b/93/K0nCKaXc_o.jpg');
INSERT INTO Image (imageID, productID, foodID, commentID, url) VALUES ('IMG000048', NULL, 'FD00048', NULL, 'https://images2.imgbox.com/6a/bc/DhwIb3jL_o.jpg');
INSERT INTO Image (imageID, productID, foodID, commentID, url) VALUES ('IMG000049', NULL, 'FD00049', NULL, 'https://images2.imgbox.com/7c/96/tDxORzZT_o.jpg');
INSERT INTO Image (imageID, productID, foodID, commentID, url) VALUES ('IMG000050', NULL, 'FD00050', NULL, 'https://images2.imgbox.com/c2/0c/mlSInYHh_o.jpg');
INSERT INTO Image (imageID, productID, foodID, commentID, url) VALUES ('IMG000051', NULL, 'FD00051', NULL, 'https://images2.imgbox.com/42/ff/Ep3BcTwu_o.jpg');
INSERT INTO Image (imageID, productID, foodID, commentID, url) VALUES ('IMG000052', NULL, 'FD00052', NULL, 'https://images2.imgbox.com/90/29/mDBSOqxc_o.jpg');
INSERT INTO Image (imageID, productID, foodID, commentID, url) VALUES ('IMG000053', NULL, 'FD00053', NULL, 'https://images2.imgbox.com/89/df/SgyNcj06_o.jpg');
INSERT INTO Image (imageID, productID, foodID, commentID, url) VALUES ('IMG000054', NULL, 'FD00054', NULL, 'https://images2.imgbox.com/59/4e/9IqHc8mo_o.jpg');
INSERT INTO Image (imageID, productID, foodID, commentID, url) VALUES ('IMG000055', NULL, 'FD00055', NULL, 'https://images2.imgbox.com/17/24/zcimqGrH_o.jpg');
INSERT INTO Image (imageID, productID, foodID, commentID, url) VALUES ('IMG000056', NULL, 'FD00056', NULL, 'https://images2.imgbox.com/2f/b8/atHm56N5_o.jpg');
INSERT INTO Image (imageID, productID, foodID, commentID, url) VALUES ('IMG000057', NULL, 'FD00057', NULL, 'https://images2.imgbox.com/81/25/OMIdon2Y_o.jpg');
INSERT INTO Image (imageID, productID, foodID, commentID, url) VALUES ('IMG000058', NULL, 'FD00058', NULL, 'https://images2.imgbox.com/53/28/cfwFBDw9_o.jpg');
INSERT INTO Image (imageID, productID, foodID, commentID, url) VALUES ('IMG000059', NULL, 'FD00059', NULL, 'https://images2.imgbox.com/49/cc/QlhGhUXd_o.jpg');
INSERT INTO Image (imageID, productID, foodID, commentID, url) VALUES ('IMG000060', NULL, 'FD00060', NULL, 'https://images2.imgbox.com/6e/ec/EExpzfu9_o.jpg');
INSERT INTO Image (imageID, productID, foodID, commentID, url) VALUES ('IMG000061', NULL, 'FD00061', NULL, 'https://images2.imgbox.com/35/95/9YfWGcq2_o.jpg');
INSERT INTO Image (imageID, productID, foodID, commentID, url) VALUES ('IMG000062', NULL, 'FD00062', NULL, 'https://images2.imgbox.com/89/1e/X8jVFEdZ_o.jpg');
INSERT INTO Image (imageID, productID, foodID, commentID, url) VALUES ('IMG000063', NULL, 'FD00063', NULL, 'https://images2.imgbox.com/13/c5/QOSHAzGN_o.jpg');
INSERT INTO Image (imageID, productID, foodID, commentID, url) VALUES ('IMG000064', NULL, 'FD00064', NULL, 'https://images2.imgbox.com/0d/8f/gSbE6WtC_o.jpg');
INSERT INTO Image (imageID, productID, foodID, commentID, url) VALUES ('IMG000065', NULL, 'FD00065', NULL, 'https://images2.imgbox.com/fe/77/KlOd1QaT_o.jpg');
INSERT INTO Image (imageID, productID, foodID, commentID, url) VALUES ('IMG000066', NULL, 'FD00066', NULL, 'https://images2.imgbox.com/1f/a3/700LLpuT_o.jpg');
INSERT INTO Image (imageID, productID, foodID, commentID, url) VALUES ('IMG000067', NULL, 'FD00067', NULL, 'https://images2.imgbox.com/fe/99/nys3jmxO_o.jpg');
INSERT INTO Image (imageID, productID, foodID, commentID, url) VALUES ('IMG000068', NULL, 'FD00068', NULL, 'https://images2.imgbox.com/4c/a4/2HhqWPZa_o.jpg');
INSERT INTO Image (imageID, productID, foodID, commentID, url) VALUES ('IMG000069', NULL, 'FD00069', NULL, 'https://images2.imgbox.com/3e/4a/K9WYuPSn_o.jpg');
INSERT INTO Image (imageID, productID, foodID, commentID, url) VALUES ('IMG000070', NULL, 'FD00070', NULL, 'https://images2.imgbox.com/d0/aa/faQ4RS2i_o.jpg');
INSERT INTO Image (imageID, productID, foodID, commentID, url) VALUES ('IMG000071', NULL, 'FD00071', NULL, 'https://images2.imgbox.com/7b/41/CVrxU8l2_o.jpg');
INSERT INTO Image (imageID, productID, foodID, commentID, url) VALUES ('IMG000072', NULL, 'FD00072', NULL, 'https://images2.imgbox.com/a4/ef/XeNSnXRj_o.jpg');
INSERT INTO Image (imageID, productID, foodID, commentID, url) VALUES ('IMG000073', NULL, 'FD00073', NULL, 'https://images2.imgbox.com/65/e3/TCfcGbNs_o.jpg');
INSERT INTO Image (imageID, productID, foodID, commentID, url) VALUES ('IMG000074', NULL, 'FD00074', NULL, 'https://images2.imgbox.com/ff/9b/QGRoM93i_o.jpg');
INSERT INTO Image (imageID, productID, foodID, commentID, url) VALUES ('IMG000075', NULL, 'FD00075', NULL, 'https://images2.imgbox.com/6c/b6/iT7ceCOJ_o.jpg');
INSERT INTO Image (imageID, productID, foodID, commentID, url) VALUES ('IMG000076', NULL, 'FD00076', NULL, 'https://images2.imgbox.com/b6/c2/t8m5VFUH_o.jpg');
INSERT INTO Image (imageID, productID, foodID, commentID, url) VALUES ('IMG000077', NULL, 'FD00077', NULL, 'https://images2.imgbox.com/1f/f5/TkZydzjL_o.jpg');
INSERT INTO Image (imageID, productID, foodID, commentID, url) VALUES ('IMG000078', NULL, 'FD00078', NULL, 'https://images2.imgbox.com/44/c5/GWqey7Hc_o.jpg');
INSERT INTO Image (imageID, productID, foodID, commentID, url) VALUES ('IMG000079', NULL, 'FD00079', NULL, 'https://images2.imgbox.com/e7/42/yzM0Pft9_o.jpg');
INSERT INTO Image (imageID, productID, foodID, commentID, url) VALUES ('IMG000080', NULL, 'FD00080', NULL, 'https://images2.imgbox.com/3b/36/WsfHg8X8_o.jpg');
INSERT INTO Image (imageID, productID, foodID, commentID, url) VALUES ('IMG000081', NULL, 'FD00081', NULL, 'https://images2.imgbox.com/04/d5/o4O8wONT_o.jpg');
INSERT INTO Image (imageID, productID, foodID, commentID, url) VALUES ('IMG000082', NULL, 'FD00082', NULL, 'https://images2.imgbox.com/1f/9e/R9fRp1hX_o.jpg');
INSERT INTO Image (imageID, productID, foodID, commentID, url) VALUES ('IMG000083', NULL, 'FD00083', NULL, 'https://images2.imgbox.com/45/a0/kArWpbcb_o.jpg');
INSERT INTO Image (imageID, productID, foodID, commentID, url) VALUES ('IMG000084', NULL, 'FD00084', NULL, 'https://images2.imgbox.com/ba/92/GwiadhqS_o.jpg');
INSERT INTO Image (imageID, productID, foodID, commentID, url) VALUES ('IMG000085', NULL, 'FD00085', NULL, 'https://images2.imgbox.com/58/3c/R0b8Oj1Z_o.jpg');
INSERT INTO Image (imageID, productID, foodID, commentID, url) VALUES ('IMG000086', NULL, 'FD00086', NULL, 'https://images2.imgbox.com/b9/dc/DHkzXtUj_o.jpg');
INSERT INTO Image (imageID, productID, foodID, commentID, url) VALUES ('IMG000087', NULL, 'FD00087', NULL, 'https://images2.imgbox.com/40/ff/UmG7CUtJ_o.jpg');
INSERT INTO Image (imageID, productID, foodID, commentID, url) VALUES ('IMG000088', NULL, 'FD00088', NULL, 'https://images2.imgbox.com/c6/c0/eKXbe0BM_o.jpg');
INSERT INTO Image (imageID, productID, foodID, commentID, url) VALUES ('IMG000089', NULL, 'FD00089', NULL, 'https://images2.imgbox.com/8d/fd/QDy88rPH_o.jpg');
INSERT INTO Image (imageID, productID, foodID, commentID, url) VALUES ('IMG000090', NULL, 'FD00090', NULL, 'https://images2.imgbox.com/53/84/6MP89WHZ_o.jpg');
INSERT INTO Image (imageID, productID, foodID, commentID, url) VALUES ('IMG000091', NULL, 'FD00091', NULL, 'https://images2.imgbox.com/33/ae/q2nzZj9w_o.jpg');
INSERT INTO Image (imageID, productID, foodID, commentID, url) VALUES ('IMG000092', NULL, 'FD00092', NULL, 'https://images2.imgbox.com/ce/fc/ewpMn73F_o.jpg');
INSERT INTO Image (imageID, productID, foodID, commentID, url) VALUES ('IMG000093', NULL, 'FD00093', NULL, 'https://images2.imgbox.com/87/2f/RuIm0BTF_o.jpg');
INSERT INTO Image (imageID, productID, foodID, commentID, url) VALUES ('IMG000094', NULL, 'FD00094', NULL, 'https://images2.imgbox.com/36/90/zYkoHqK3_o.jpg');
INSERT INTO Image (imageID, productID, foodID, commentID, url) VALUES ('IMG000095', NULL, 'FD00095', NULL, 'https://images2.imgbox.com/81/59/r8POSYR6_o.jpg');
INSERT INTO Image (imageID, productID, foodID, commentID, url) VALUES ('IMG000096', NULL, 'FD00096', NULL, 'https://images2.imgbox.com/84/d6/iZTGwwm6_o.jpg');
INSERT INTO Image (imageID, productID, foodID, commentID, url) VALUES ('IMG000097', NULL, 'FD00097', NULL, 'https://images2.imgbox.com/63/f3/DjCXWB0v_o.jpg');
INSERT INTO Image (imageID, productID, foodID, commentID, url) VALUES ('IMG000098', NULL, 'FD00098', NULL, 'https://images2.imgbox.com/9e/59/XczCbrWL_o.jpg');
INSERT INTO Image (imageID, productID, foodID, commentID, url) VALUES ('IMG000099', NULL, 'FD00099', NULL, 'https://images2.imgbox.com/9d/05/gbWwQYqp_o.jpg');
INSERT INTO Image (imageID, productID, foodID, commentID, url) VALUES ('IMG000100', NULL, 'FD00100', NULL, 'https://images2.imgbox.com/13/23/FZmomMMH_o.jpg');
INSERT INTO Image (imageID, productID, foodID, commentID, url) VALUES ('IMG000101', NULL, 'FD00101', NULL, 'https://images2.imgbox.com/f3/84/UuFQLujB_o.jpg');
INSERT INTO Image (imageID, productID, foodID, commentID, url) VALUES ('IMG000102', NULL, 'FD00102', NULL, 'https://images2.imgbox.com/50/bc/rhiSou6X_o.jpg');
INSERT INTO Image (imageID, productID, foodID, commentID, url) VALUES ('IMG000103', NULL, 'FD00103', NULL, 'https://images2.imgbox.com/6e/56/hk3INfDq_o.jpg');
INSERT INTO Image (imageID, productID, foodID, commentID, url) VALUES ('IMG000104', NULL, 'FD00104', NULL, 'https://images2.imgbox.com/18/08/T0dWtOix_o.jpg');
INSERT INTO Image (imageID, productID, foodID, commentID, url) VALUES ('IMG000105', NULL, 'FD00105', NULL, 'https://images2.imgbox.com/a7/d2/KjNdTM5i_o.jpg');
INSERT INTO Image (imageID, productID, foodID, commentID, url) VALUES ('IMG000106', NULL, 'FD00106', NULL, 'https://images2.imgbox.com/8c/59/zKcgPBso_o.jpg');
INSERT INTO Image (imageID, productID, foodID, commentID, url) VALUES ('IMG000107', NULL, 'FD00107', NULL, 'https://images2.imgbox.com/2d/f8/FrOFdhIg_o.jpg');
INSERT INTO Image (imageID, productID, foodID, commentID, url) VALUES ('IMG000108', NULL, 'FD00108', NULL, 'https://images2.imgbox.com/33/d7/zHrgUSBv_o.jpg');
INSERT INTO Image (imageID, productID, foodID, commentID, url) VALUES ('IMG000109', NULL, 'FD00109', NULL, 'https://images2.imgbox.com/14/f2/0Y5DbXqE_o.jpg');
INSERT INTO Image (imageID, productID, foodID, commentID, url) VALUES ('IMG000110', NULL, 'FD00110', NULL, 'https://images2.imgbox.com/c7/8e/WrfoFyMN_o.jpg');
INSERT INTO Image (imageID, productID, foodID, commentID, url) VALUES ('IMG000111', NULL, 'FD00111', NULL, 'https://images2.imgbox.com/0c/9d/eUMMIWbi_o.jpg');
INSERT INTO Image (imageID, productID, foodID, commentID, url) VALUES ('IMG000112', NULL, 'FD00112', NULL, 'https://images2.imgbox.com/6e/3f/7C6rQYR2_o.jpg');
INSERT INTO Image (imageID, productID, foodID, commentID, url) VALUES ('IMG000113', NULL, 'FD00113', NULL, 'https://images2.imgbox.com/8a/65/DYUVKSpa_o.jpg');
INSERT INTO Image (imageID, productID, foodID, commentID, url) VALUES ('IMG000114', NULL, 'FD00114', NULL, 'https://images2.imgbox.com/1a/98/hfKWn6Ky_o.jpg');
INSERT INTO Image (imageID, productID, foodID, commentID, url) VALUES ('IMG000115', NULL, 'FD00115', NULL, 'https://images2.imgbox.com/55/aa/jbwQeS6e_o.jpg');
INSERT INTO Image (imageID, productID, foodID, commentID, url) VALUES ('IMG000116', NULL, 'FD00116', NULL, 'https://images2.imgbox.com/ad/23/HnyXAkvY_o.jpg');
INSERT INTO Image (imageID, productID, foodID, commentID, url) VALUES ('IMG000117', NULL, 'FD00117', NULL, 'https://images2.imgbox.com/02/5a/tiYilSD6_o.jpg');
INSERT INTO Image (imageID, productID, foodID, commentID, url) VALUES ('IMG000118', NULL, 'FD00118', NULL, 'https://images2.imgbox.com/c0/39/9E0vIuOt_o.jpg');
INSERT INTO Image (imageID, productID, foodID, commentID, url) VALUES ('IMG000119', NULL, 'FD00119', NULL, 'https://images2.imgbox.com/53/68/GykdJxoO_o.jpg');
INSERT INTO Image (imageID, productID, foodID, commentID, url) VALUES ('IMG000120', NULL, 'FD00120', NULL, 'https://images2.imgbox.com/d8/66/HRBSQsvF_o.jpg');
INSERT INTO Image (imageID, productID, foodID, commentID, url) VALUES ('IMG000121', NULL, 'FD00121', NULL, 'https://images2.imgbox.com/ab/df/goM9dwME_o.jpg');
INSERT INTO Image (imageID, productID, foodID, commentID, url) VALUES ('IMG000122', NULL, 'FD00122', NULL, 'https://images2.imgbox.com/00/2a/AKSRbzHc_o.jpg');
INSERT INTO Image (imageID, productID, foodID, commentID, url) VALUES ('IMG000123', NULL, 'FD00123', NULL, 'https://images2.imgbox.com/4b/d4/Zd2Nhpk0_o.jpg');
INSERT INTO Image (imageID, productID, foodID, commentID, url) VALUES ('IMG000124', NULL, 'FD00124', NULL, 'https://images2.imgbox.com/55/6e/x3dIakCc_o.jpg');
INSERT INTO Image (imageID, productID, foodID, commentID, url) VALUES ('IMG000125', NULL, 'FD00125', NULL, 'https://images2.imgbox.com/aa/51/sNaGlWRy_o.jpg');
INSERT INTO Image (imageID, productID, foodID, commentID, url) VALUES ('IMG000126', NULL, 'FD00126', NULL, 'https://images2.imgbox.com/06/27/vrtpJNs1_o.jpg');
INSERT INTO Image (imageID, productID, foodID, commentID, url) VALUES ('IMG000127', NULL, 'FD00127', NULL, 'https://images2.imgbox.com/0a/c7/xKwFTJ0f_o.jpg');
INSERT INTO Image (imageID, productID, foodID, commentID, url) VALUES ('IMG000128', NULL, 'FD00128', NULL, 'https://images2.imgbox.com/b6/99/ORwmohgc_o.jpg');
INSERT INTO Image (imageID, productID, foodID, commentID, url) VALUES ('IMG000129', NULL, 'FD00129', NULL, 'https://images2.imgbox.com/c4/83/kWpmOtUV_o.jpg');
INSERT INTO Image (imageID, productID, foodID, commentID, url) VALUES ('IMG000130', NULL, 'FD00130', NULL, 'https://images2.imgbox.com/a7/9b/mXR4dmHH_o.jpg');
INSERT INTO Image (imageID, productID, foodID, commentID, url) VALUES ('IMG000131', NULL, 'FD00131', NULL, 'https://images2.imgbox.com/f7/08/dJ1mrMhh_o.jpg');
INSERT INTO Image (imageID, productID, foodID, commentID, url) VALUES ('IMG000132', NULL, 'FD00132', NULL, 'https://images2.imgbox.com/0e/f6/Av7tqyAb_o.jpg');
INSERT INTO Image (imageID, productID, foodID, commentID, url) VALUES ('IMG000133', NULL, 'FD00133', NULL, 'https://images2.imgbox.com/5b/17/JdhLljut_o.jpg');
INSERT INTO Image (imageID, productID, foodID, commentID, url) VALUES ('IMG000134', NULL, 'FD00134', NULL, 'https://images2.imgbox.com/39/7a/z5XCmF5l_o.jpg');
INSERT INTO Image (imageID, productID, foodID, commentID, url) VALUES ('IMG000135', NULL, 'FD00135', NULL, 'https://images2.imgbox.com/e6/ed/BapmQ9Zs_o.jpg');
INSERT INTO Image (imageID, productID, foodID, commentID, url) VALUES ('IMG000136', NULL, 'FD00136', NULL, 'https://images2.imgbox.com/78/95/exGMFmu5_o.jpg');
INSERT INTO Image (imageID, productID, foodID, commentID, url) VALUES ('IMG000137', NULL, 'FD00137', NULL, 'https://images2.imgbox.com/82/8f/XJB0QHmV_o.jpg');
INSERT INTO Image (imageID, productID, foodID, commentID, url) VALUES ('IMG000138', NULL, 'FD00138', NULL, 'https://images2.imgbox.com/d5/73/959y5L7y_o.jpg');
INSERT INTO Image (imageID, productID, foodID, commentID, url) VALUES ('IMG000139', NULL, 'FD00139', NULL, 'https://images2.imgbox.com/5f/50/7W3AbdOo_o.jpg');
INSERT INTO Image (imageID, productID, foodID, commentID, url) VALUES ('IMG000140', NULL, 'FD00140', NULL, 'https://images2.imgbox.com/8d/29/emVIoZRn_o.jpg');
INSERT INTO Image (imageID, productID, foodID, commentID, url) VALUES ('IMG000141', NULL, 'FD00141', NULL, 'https://images2.imgbox.com/9b/d3/7uPuKdH6_o.jpg');
INSERT INTO Image (imageID, productID, foodID, commentID, url) VALUES ('IMG000142', NULL, 'FD00142', NULL, 'https://images2.imgbox.com/c1/dd/0xCHm51e_o.jpg');
INSERT INTO Image (imageID, productID, foodID, commentID, url) VALUES ('IMG000143', NULL, 'FD00143', NULL, 'https://images2.imgbox.com/9f/29/Z3oIxYKn_o.jpg');
INSERT INTO Image (imageID, productID, foodID, commentID, url) VALUES ('IMG000144', NULL, 'FD00144', NULL, 'https://images2.imgbox.com/d4/7a/dVdVZ7Df_o.jpg');
INSERT INTO Image (imageID, productID, foodID, commentID, url) VALUES ('IMG000145', NULL, 'FD00145', NULL, 'https://images2.imgbox.com/e2/88/JP8FI29J_o.jpg');
INSERT INTO Image (imageID, productID, foodID, commentID, url) VALUES ('IMG000146', NULL, 'FD00146', NULL, 'https://images2.imgbox.com/91/f1/zyM1kQQu_o.jpg');
INSERT INTO Image (imageID, productID, foodID, commentID, url) VALUES ('IMG000147', NULL, 'FD00147', NULL, 'https://images2.imgbox.com/82/c8/ctiGQuin_o.jpg');
INSERT INTO Image (imageID, productID, foodID, commentID, url) VALUES ('IMG000148', NULL, 'FD00148', NULL, 'https://images2.imgbox.com/1a/d2/iQ046n0H_o.jpg');
INSERT INTO Image (imageID, productID, foodID, commentID, url) VALUES ('IMG000149', NULL, 'FD00149', NULL, 'https://images2.imgbox.com/99/da/b34QDU3X_o.jpg');
INSERT INTO Image (imageID, productID, foodID, commentID, url) VALUES ('IMG000150', NULL, 'FD00150', NULL, 'https://images2.imgbox.com/00/c1/YBQiRrC4_o.jpg');
INSERT INTO Image (imageID, productID, foodID, commentID, url) VALUES ('IMG000151', NULL, 'FD00151', NULL, 'https://images2.imgbox.com/62/bc/zFIB1KoK_o.jpg');
INSERT INTO Image (imageID, productID, foodID, commentID, url) VALUES ('IMG000152', NULL, 'FD00152', NULL, 'https://images2.imgbox.com/9d/e5/gLUHlEk9_o.jpg');
INSERT INTO Image (imageID, productID, foodID, commentID, url) VALUES ('IMG000153', NULL, 'FD00153', NULL, 'https://images2.imgbox.com/2f/5b/Tv8W0gOe_o.jpg');
INSERT INTO Image (imageID, productID, foodID, commentID, url) VALUES ('IMG000154', NULL, 'FD00154', NULL, 'https://images2.imgbox.com/1d/e9/zZUSG8pw_o.jpg');
INSERT INTO Image (imageID, productID, foodID, commentID, url) VALUES ('IMG000155', NULL, 'FD00155', NULL, 'https://images2.imgbox.com/0c/c9/WChZxhuS_o.jpg');
INSERT INTO Image (imageID, productID, foodID, commentID, url) VALUES ('IMG000156', NULL, 'FD00156', NULL, 'https://images2.imgbox.com/93/e5/DAcpjKXh_o.jpg');
INSERT INTO Image (imageID, productID, foodID, commentID, url) VALUES ('IMG000157', NULL, 'FD00157', NULL, 'https://images2.imgbox.com/d4/fb/WPQiKTM9_o.jpg');
INSERT INTO Image (imageID, productID, foodID, commentID, url) VALUES ('IMG000158', NULL, 'FD00158', NULL, 'https://images2.imgbox.com/70/12/PGZz2tKt_o.jpg');
INSERT INTO Image (imageID, productID, foodID, commentID, url) VALUES ('IMG000159', NULL, 'FD00159', NULL, 'https://images2.imgbox.com/66/f1/bir4Qs6b_o.jpg');
INSERT INTO Image (imageID, productID, foodID, commentID, url) VALUES ('IMG000160', NULL, 'FD00160', NULL, 'https://images2.imgbox.com/b5/e6/rEuBmgsX_o.jpg');
INSERT INTO Image (imageID, productID, foodID, commentID, url) VALUES ('IMG000161', NULL, 'FD00161', NULL, 'https://images2.imgbox.com/77/ee/3EyJYkbg_o.jpg');
INSERT INTO Image (imageID, productID, foodID, commentID, url) VALUES ('IMG000162', NULL, 'FD00162', NULL, 'https://images2.imgbox.com/1d/8b/ykqbtQQS_o.jpg');
INSERT INTO Image (imageID, productID, foodID, commentID, url) VALUES ('IMG000163', NULL, 'FD00163', NULL, 'https://images2.imgbox.com/ea/78/umyQD8H1_o.jpg');
INSERT INTO Image (imageID, productID, foodID, commentID, url) VALUES ('IMG000164', NULL, 'FD00164', NULL, 'https://images2.imgbox.com/41/44/TnWkL8DA_o.jpg');
INSERT INTO Image (imageID, productID, foodID, commentID, url) VALUES ('IMG000165', NULL, 'FD00165', NULL, 'https://images2.imgbox.com/20/10/m3d8eKQT_o.jpg');
INSERT INTO Image (imageID, productID, foodID, commentID, url) VALUES ('IMG000166', NULL, 'FD00166', NULL, 'https://images2.imgbox.com/41/06/QCzWX7r9_o.jpg');
INSERT INTO Image (imageID, productID, foodID, commentID, url) VALUES ('IMG000167', NULL, 'FD00167', NULL, 'https://images2.imgbox.com/d6/6e/lYzXAELn_o.jpg');
INSERT INTO Image (imageID, productID, foodID, commentID, url) VALUES ('IMG000168', NULL, 'FD00168', NULL, 'https://images2.imgbox.com/b2/b4/dLtE7Rvj_o.jpg');
INSERT INTO Image (imageID, productID, foodID, commentID, url) VALUES ('IMG000169', NULL, 'FD00169', NULL, 'https://images2.imgbox.com/6b/c0/J2NBDSjR_o.jpg');
INSERT INTO Image (imageID, productID, foodID, commentID, url) VALUES ('IMG000170', NULL, 'FD00170', NULL, 'https://images2.imgbox.com/4b/92/nJB6NySp_o.jpg');
INSERT INTO Image (imageID, productID, foodID, commentID, url) VALUES ('IMG000171', NULL, 'FD00171', NULL, 'https://images2.imgbox.com/67/e2/CnsaeAga_o.jpg');
INSERT INTO Image (imageID, productID, foodID, commentID, url) VALUES ('IMG000172', NULL, 'FD00172', NULL, 'https://images2.imgbox.com/57/e7/tr9ZeGim_o.jpg');
INSERT INTO Image (imageID, productID, foodID, commentID, url) VALUES ('IMG000173', NULL, 'FD00173', NULL, 'https://images2.imgbox.com/09/24/yEkodP6H_o.jpg');
INSERT INTO Image (imageID, productID, foodID, commentID, url) VALUES ('IMG000174', NULL, 'FD00174', NULL, 'https://images2.imgbox.com/95/4e/xSEZyw8m_o.jpg');
INSERT INTO Image (imageID, productID, foodID, commentID, url) VALUES ('IMG000175', NULL, 'FD00175', NULL, 'https://images2.imgbox.com/b3/5d/cSNXE28C_o.jpg');
INSERT INTO Image (imageID, productID, foodID, commentID, url) VALUES ('IMG000176', NULL, 'FD00176', NULL, 'https://images2.imgbox.com/8f/fe/u9yI6S3k_o.jpg');
INSERT INTO Image (imageID, productID, foodID, commentID, url) VALUES ('IMG000177', NULL, 'FD00177', NULL, 'https://images2.imgbox.com/79/27/tqxoBiXd_o.jpg');
INSERT INTO Image (imageID, productID, foodID, commentID, url) VALUES ('IMG000178', NULL, 'FD00178', NULL, 'https://images2.imgbox.com/73/7d/KX025t7o_o.jpg');
INSERT INTO Image (imageID, productID, foodID, commentID, url) VALUES ('IMG000179', NULL, 'FD00179', NULL, 'https://images2.imgbox.com/2b/b1/TJvVNyaI_o.jpg');
INSERT INTO Image (imageID, productID, foodID, commentID, url) VALUES ('IMG000180', NULL, 'FD00180', NULL, 'https://images2.imgbox.com/1c/91/hAzor4xy_o.jpg');
INSERT INTO Image (imageID, productID, foodID, commentID, url) VALUES ('IMG000181', NULL, 'FD00181', NULL, 'https://images2.imgbox.com/07/3b/ckXkaAjy_o.jpg');
INSERT INTO Image (imageID, productID, foodID, commentID, url) VALUES ('IMG000182', NULL, 'FD00182', NULL, 'https://images2.imgbox.com/83/c5/hXtJhT9B_o.jpg');
INSERT INTO Image (imageID, productID, foodID, commentID, url) VALUES ('IMG000183', NULL, 'FD00183', NULL, 'https://images2.imgbox.com/7b/7b/YoLLqIYj_o.jpg');
INSERT INTO Image (imageID, productID, foodID, commentID, url) VALUES ('IMG000184', NULL, 'FD00184', NULL, 'https://images2.imgbox.com/a9/33/k0K3iENC_o.jpg');
INSERT INTO Image (imageID, productID, foodID, commentID, url) VALUES ('IMG000185', NULL, 'FD00185', NULL, 'https://images2.imgbox.com/6d/4e/hzBhjFKa_o.jpg');
INSERT INTO Image (imageID, productID, foodID, commentID, url) VALUES ('IMG000186', NULL, 'FD00186', NULL, 'https://images2.imgbox.com/ea/5b/YDX7XX6r_o.jpg');
INSERT INTO Image (imageID, productID, foodID, commentID, url) VALUES ('IMG000187', NULL, 'FD00187', NULL, 'https://images2.imgbox.com/41/59/2ckmz6gt_o.jpg');
INSERT INTO Image (imageID, productID, foodID, commentID, url) VALUES ('IMG000188', NULL, 'FD00188', NULL, 'https://images2.imgbox.com/98/a6/81T2Oo2o_o.jpg');
INSERT INTO Image (imageID, productID, foodID, commentID, url) VALUES ('IMG000189', NULL, 'FD00189', NULL, 'https://images2.imgbox.com/a4/3f/afsEZEkb_o.jpg');
INSERT INTO Image (imageID, productID, foodID, commentID, url) VALUES ('IMG000190', NULL, 'FD00190', NULL, 'https://images2.imgbox.com/9a/3b/Jn7vzo9I_o.jpg');
INSERT INTO Image (imageID, productID, foodID, commentID, url) VALUES ('IMG000191', NULL, 'FD00191', NULL, 'https://images2.imgbox.com/ec/51/gvgyVF6R_o.jpg');
INSERT INTO Image (imageID, productID, foodID, commentID, url) VALUES ('IMG000192', NULL, 'FD00192', NULL, 'https://images2.imgbox.com/0f/04/JAh2ibzt_o.jpg');
INSERT INTO Image (imageID, productID, foodID, commentID, url) VALUES ('IMG000193', NULL, 'FD00193', NULL, 'https://images2.imgbox.com/55/9d/BU3ZISrK_o.jpg');
INSERT INTO Image (imageID, productID, foodID, commentID, url) VALUES ('IMG000194', NULL, 'FD00194', NULL, 'https://images2.imgbox.com/d4/de/ILYnRT2X_o.jpg');
INSERT INTO Image (imageID, productID, foodID, commentID, url) VALUES ('IMG000195', NULL, 'FD00195', NULL, 'https://images2.imgbox.com/5a/dc/t3so4xJh_o.jpg');
INSERT INTO Image (imageID, productID, foodID, commentID, url) VALUES ('IMG000196', NULL, 'FD00196', NULL, 'https://images2.imgbox.com/2b/41/18EIZUtj_o.jpg');
INSERT INTO Image (imageID, productID, foodID, commentID, url) VALUES ('IMG000197', NULL, 'FD00197', NULL, 'https://images2.imgbox.com/6e/cc/PN0mI3Tk_o.jpg');
INSERT INTO Image (imageID, productID, foodID, commentID, url) VALUES ('IMG000198', NULL, 'FD00198', NULL, 'https://images2.imgbox.com/e5/cc/rjetYiVE_o.jpg');
INSERT INTO Image (imageID, productID, foodID, commentID, url) VALUES ('IMG000199', NULL, 'FD00199', NULL, 'https://images2.imgbox.com/50/86/A3mzX4EI_o.jpg');
INSERT INTO Image (imageID, productID, foodID, commentID, url) VALUES ('IMG000200', NULL, 'FD00200', NULL, 'https://images2.imgbox.com/e9/db/jY15rZ37_o.jpg');
INSERT INTO Image (imageID, productID, foodID, commentID, url) VALUES ('IMG000201', NULL, 'FD00201', NULL, 'https://images2.imgbox.com/8b/f5/csnJwBiw_o.jpg');
INSERT INTO Image (imageID, productID, foodID, commentID, url) VALUES ('IMG000202', NULL, 'FD00202', NULL, 'https://images2.imgbox.com/bd/d8/5HlEKIQW_o.jpg');
INSERT INTO Image (imageID, productID, foodID, commentID, url) VALUES ('IMG000203', NULL, 'FD00203', NULL, 'https://images2.imgbox.com/9d/f4/YylnEY21_o.jpg');
INSERT INTO Image (imageID, productID, foodID, commentID, url) VALUES ('IMG000204', NULL, 'FD00204', NULL, 'https://images2.imgbox.com/41/59/2ckmz6gt_o.jpg');
INSERT INTO Image (imageID, productID, foodID, commentID, url) VALUES ('IMG000205', NULL, 'FD00205', NULL, 'https://images2.imgbox.com/b6/d2/P4EKS5Wo_o.jpg');
INSERT INTO Image (imageID, productID, foodID, commentID, url) VALUES ('IMG000206', NULL, 'FD00206', NULL, 'https://images2.imgbox.com/b4/29/nqxV8f52_o.jpg');

--INSERT POPUP
INSERT INTO PopUp (popupID, [description], [status], theme) VALUES ('POP001', N'Dành cho người dùng mới', 1, '')

--INSERT POPUPDETAIL
INSERT INTO PopUpDetail(popupID, productID, [description]) VALUES ('POP001', 'PRO0001', N'Dành cho người dùng mới')

--INSERT ImageProduct
INSERT INTO Image (imageID, productID, foodID, commentID, url) VALUES ('IMG000207', 'PRO0001',null , NULL, 'https://thumbs2.imgbox.com/9f/2d/f26fX97L_t.jpg');
INSERT INTO Image (imageID, productID, foodID, commentID, url) VALUES ('IMG000208', 'PRO0006',null , NULL, 'https://thumbs2.imgbox.com/ae/32/LpHFYjf8_t.jpg');
INSERT INTO Image (imageID, productID, foodID, commentID, url) VALUES ('IMG000209', 'PRO0007',null , NULL, 'https://thumbs2.imgbox.com/e6/60/ta0eXMyh_t.jpg');
INSERT INTO Image (imageID, productID, foodID, commentID, url) VALUES ('IMG000210', 'PRO0008',null , NULL, 'https://thumbs2.imgbox.com/3a/23/Sh8tWZdG_t.jpg');
INSERT INTO Image (imageID, productID, foodID, commentID, url) VALUES ('IMG000211', 'PRO0009',null , NULL, 'https://thumbs2.imgbox.com/0f/bf/hj1Pkidr_t.jpg');
INSERT INTO Image (imageID, productID, foodID, commentID, url) VALUES ('IMG000212', 'PRO0010',null , NULL, 'https://thumbs2.imgbox.com/f1/68/LYzuXjKo_t.jpg');
INSERT INTO Image (imageID, productID, foodID, commentID, url) VALUES ('IMG000213', 'PRO0011',null , NULL, 'https://thumbs2.imgbox.com/1f/86/I6Eh6gsu_t.jpg');
INSERT INTO Image (imageID, productID, foodID, commentID, url) VALUES ('IMG000214', 'PRO0012',null , NULL, 'https://thumbs2.imgbox.com/52/6b/HCiZsSzI_t.jpg');
INSERT INTO Image (imageID, productID, foodID, commentID, url) VALUES ('IMG000215', 'PRO0013',null , NULL, 'https://thumbs2.imgbox.com/f4/9d/xvBrZH4v_t.jpg');
INSERT INTO Image (imageID, productID, foodID, commentID, url) VALUES ('IMG000216', 'PRO0014',null , NULL, 'https://thumbs2.imgbox.com/d3/72/q23C9z8R_t.jpg');
INSERT INTO Image (imageID, productID, foodID, commentID, url) VALUES ('IMG000217', 'PRO0015',null , NULL, 'https://thumbs2.imgbox.com/9e/6a/PrwYmncw_t.jpg');
INSERT INTO Image (imageID, productID, foodID, commentID, url) VALUES ('IMG000218', 'PRO0016',null , NULL, 'https://thumbs2.imgbox.com/33/02/tSuW4Hst_t.jpg');
INSERT INTO Image (imageID, productID, foodID, commentID, url) VALUES ('IMG000219', 'PRO0017',null , NULL, 'https://thumbs2.imgbox.com/7a/20/MJczSJTk_t.jpg');
INSERT INTO Image (imageID, productID, foodID, commentID, url) VALUES ('IMG000222', 'PRO0018',null , NULL, 'https://thumbs2.imgbox.com/e2/5e/l0UTogpu_t.jpg');
INSERT INTO Image (imageID, productID, foodID, commentID, url) VALUES ('IMG000221', 'PRO0019',null , NULL, 'https://thumbs2.imgbox.com/2f/10/AQ3xgaIb_t.jpg');
INSERT INTO Image (imageID, productID, foodID, commentID, url) VALUES ('IMG000222', 'PRO0020',null , NULL, 'https://thumbs2.imgbox.com/69/80/Nq5Xyp2V_t.jpg');
